<?php

namespace Mpdf\Shaper;

use Mpdf\Fonts\GlyphString;

/**
 * Arabic and Syriac cursive joining.
 *
 * Every other script reaches its positional forms through GSUB: the font carries isol/fina/medi/init
 * lookups and Otl applies them like any other feature. Arabic and Syriac do not - mPDF resolves the
 * form here from the Unicode joining classes, then substitutes the glyph the font's rtlSUB table
 * names for it. So this stands in place of those four features rather than alongside them, and of the
 * fin2/fin3/med2 Syriac adds for the Alaph.
 *
 * @see https://unicode.org/Public/UNIDATA/ArabicShaping.txt
 * @see https://unicode.org/Public/UNIDATA/extracted/DerivedJoiningType.txt
 */
class Arabic
{

	/**
	 * The characters that join to the letter written after them, which is what an initial or a medial
	 * form is drawn for: Unicode's Left-Joining, Dual-Joining and Join_Causing types.
	 *
	 * This and $rightJoining are generated by composer arabicjoining:update from the Joining_Type
	 * property - see tests/Mpdf/ArabicJoining.php. Missing from both tables, a character joins nothing
	 * and unjoins its neighbour, so the hand-written lists these replaced drew the letter before a
	 * recently added one with no form at all (#251).
	 */
	// UNIDATA_VERSION 17.0.0
	public static $leftJoining = [
		0x0620 => 1, 0x0626 => 1, 0x0628 => 1, 0x062A => 1, 0x062B => 1, 0x062C => 1, 0x062D => 1, 0x062E => 1,
		0x0633 => 1, 0x0634 => 1, 0x0635 => 1, 0x0636 => 1, 0x0637 => 1, 0x0638 => 1, 0x0639 => 1, 0x063A => 1,
		0x063B => 1, 0x063C => 1, 0x063D => 1, 0x063E => 1, 0x063F => 1, 0x0640 => 1, 0x0641 => 1, 0x0642 => 1,
		0x0643 => 1, 0x0644 => 1, 0x0645 => 1, 0x0646 => 1, 0x0647 => 1, 0x0649 => 1, 0x064A => 1, 0x066E => 1,
		0x066F => 1, 0x0678 => 1, 0x0679 => 1, 0x067A => 1, 0x067B => 1, 0x067C => 1, 0x067D => 1, 0x067E => 1,
		0x067F => 1, 0x0680 => 1, 0x0681 => 1, 0x0682 => 1, 0x0683 => 1, 0x0684 => 1, 0x0685 => 1, 0x0686 => 1,
		0x0687 => 1, 0x069A => 1, 0x069B => 1, 0x069C => 1, 0x069D => 1, 0x069E => 1, 0x069F => 1, 0x06A0 => 1,
		0x06A1 => 1, 0x06A2 => 1, 0x06A3 => 1, 0x06A4 => 1, 0x06A5 => 1, 0x06A6 => 1, 0x06A7 => 1, 0x06A8 => 1,
		0x06A9 => 1, 0x06AA => 1, 0x06AB => 1, 0x06AC => 1, 0x06AD => 1, 0x06AE => 1, 0x06AF => 1, 0x06B0 => 1,
		0x06B1 => 1, 0x06B2 => 1, 0x06B3 => 1, 0x06B4 => 1, 0x06B5 => 1, 0x06B6 => 1, 0x06B7 => 1, 0x06B8 => 1,
		0x06B9 => 1, 0x06BA => 1, 0x06BB => 1, 0x06BC => 1, 0x06BD => 1, 0x06BE => 1, 0x06BF => 1, 0x06C1 => 1,
		0x06C2 => 1, 0x06CC => 1, 0x06CE => 1, 0x06D0 => 1, 0x06D1 => 1, 0x06FA => 1, 0x06FB => 1, 0x06FC => 1,
		0x06FF => 1, 0x0712 => 1, 0x0713 => 1, 0x0714 => 1, 0x071A => 1, 0x071B => 1, 0x071C => 1, 0x071D => 1,
		0x071F => 1, 0x0720 => 1, 0x0721 => 1, 0x0722 => 1, 0x0723 => 1, 0x0724 => 1, 0x0725 => 1, 0x0726 => 1,
		0x0727 => 1, 0x0729 => 1, 0x072B => 1, 0x072D => 1, 0x072E => 1, 0x074E => 1, 0x074F => 1, 0x0750 => 1,
		0x0751 => 1, 0x0752 => 1, 0x0753 => 1, 0x0754 => 1, 0x0755 => 1, 0x0756 => 1, 0x0757 => 1, 0x0758 => 1,
		0x075C => 1, 0x075D => 1, 0x075E => 1, 0x075F => 1, 0x0760 => 1, 0x0761 => 1, 0x0762 => 1, 0x0763 => 1,
		0x0764 => 1, 0x0765 => 1, 0x0766 => 1, 0x0767 => 1, 0x0768 => 1, 0x0769 => 1, 0x076A => 1, 0x076D => 1,
		0x076E => 1, 0x076F => 1, 0x0770 => 1, 0x0772 => 1, 0x0775 => 1, 0x0776 => 1, 0x0777 => 1, 0x077A => 1,
		0x077B => 1, 0x077C => 1, 0x077D => 1, 0x077E => 1, 0x077F => 1, 0x07CA => 1, 0x07CB => 1, 0x07CC => 1,
		0x07CD => 1, 0x07CE => 1, 0x07CF => 1, 0x07D0 => 1, 0x07D1 => 1, 0x07D2 => 1, 0x07D3 => 1, 0x07D4 => 1,
		0x07D5 => 1, 0x07D6 => 1, 0x07D7 => 1, 0x07D8 => 1, 0x07D9 => 1, 0x07DA => 1, 0x07DB => 1, 0x07DC => 1,
		0x07DD => 1, 0x07DE => 1, 0x07DF => 1, 0x07E0 => 1, 0x07E1 => 1, 0x07E2 => 1, 0x07E3 => 1, 0x07E4 => 1,
		0x07E5 => 1, 0x07E6 => 1, 0x07E7 => 1, 0x07E8 => 1, 0x07E9 => 1, 0x07EA => 1, 0x07FA => 1, 0x0841 => 1,
		0x0842 => 1, 0x0843 => 1, 0x0844 => 1, 0x0845 => 1, 0x0848 => 1, 0x084A => 1, 0x084B => 1, 0x084C => 1,
		0x084D => 1, 0x084E => 1, 0x084F => 1, 0x0850 => 1, 0x0851 => 1, 0x0852 => 1, 0x0853 => 1, 0x0855 => 1,
		0x0860 => 1, 0x0862 => 1, 0x0863 => 1, 0x0864 => 1, 0x0865 => 1, 0x0868 => 1, 0x0883 => 1, 0x0884 => 1,
		0x0885 => 1, 0x0886 => 1, 0x0889 => 1, 0x088A => 1, 0x088B => 1, 0x088C => 1, 0x088D => 1, 0x088F => 1,
		0x08A0 => 1, 0x08A1 => 1, 0x08A2 => 1, 0x08A3 => 1, 0x08A4 => 1, 0x08A5 => 1, 0x08A6 => 1, 0x08A7 => 1,
		0x08A8 => 1, 0x08A9 => 1, 0x08AF => 1, 0x08B0 => 1, 0x08B3 => 1, 0x08B4 => 1, 0x08B5 => 1, 0x08B6 => 1,
		0x08B7 => 1, 0x08B8 => 1, 0x08BA => 1, 0x08BB => 1, 0x08BC => 1, 0x08BD => 1, 0x08BE => 1, 0x08BF => 1,
		0x08C0 => 1, 0x08C1 => 1, 0x08C2 => 1, 0x08C3 => 1, 0x08C4 => 1, 0x08C5 => 1, 0x08C6 => 1, 0x08C7 => 1,
		0x08C8 => 1, 0x200D => 1, 0x10EC3 => 1, 0x10EC4 => 1, 0x10EC6 => 1, 0x10EC7 => 1,
	];

	/**
	 * The characters that join to the letter written before them, which is what a final or a medial form
	 * is drawn for: Unicode's Right-Joining, Dual-Joining and Join_Causing types.
	 */
	public static $rightJoining = [
		0x0620 => 1, 0x0622 => 1, 0x0623 => 1, 0x0624 => 1, 0x0625 => 1, 0x0626 => 1, 0x0627 => 1, 0x0628 => 1,
		0x0629 => 1, 0x062A => 1, 0x062B => 1, 0x062C => 1, 0x062D => 1, 0x062E => 1, 0x062F => 1, 0x0630 => 1,
		0x0631 => 1, 0x0632 => 1, 0x0633 => 1, 0x0634 => 1, 0x0635 => 1, 0x0636 => 1, 0x0637 => 1, 0x0638 => 1,
		0x0639 => 1, 0x063A => 1, 0x063B => 1, 0x063C => 1, 0x063D => 1, 0x063E => 1, 0x063F => 1, 0x0640 => 1,
		0x0641 => 1, 0x0642 => 1, 0x0643 => 1, 0x0644 => 1, 0x0645 => 1, 0x0646 => 1, 0x0647 => 1, 0x0648 => 1,
		0x0649 => 1, 0x064A => 1, 0x066E => 1, 0x066F => 1, 0x0671 => 1, 0x0672 => 1, 0x0673 => 1, 0x0675 => 1,
		0x0676 => 1, 0x0677 => 1, 0x0678 => 1, 0x0679 => 1, 0x067A => 1, 0x067B => 1, 0x067C => 1, 0x067D => 1,
		0x067E => 1, 0x067F => 1, 0x0680 => 1, 0x0681 => 1, 0x0682 => 1, 0x0683 => 1, 0x0684 => 1, 0x0685 => 1,
		0x0686 => 1, 0x0687 => 1, 0x0688 => 1, 0x0689 => 1, 0x068A => 1, 0x068B => 1, 0x068C => 1, 0x068D => 1,
		0x068E => 1, 0x068F => 1, 0x0690 => 1, 0x0691 => 1, 0x0692 => 1, 0x0693 => 1, 0x0694 => 1, 0x0695 => 1,
		0x0696 => 1, 0x0697 => 1, 0x0698 => 1, 0x0699 => 1, 0x069A => 1, 0x069B => 1, 0x069C => 1, 0x069D => 1,
		0x069E => 1, 0x069F => 1, 0x06A0 => 1, 0x06A1 => 1, 0x06A2 => 1, 0x06A3 => 1, 0x06A4 => 1, 0x06A5 => 1,
		0x06A6 => 1, 0x06A7 => 1, 0x06A8 => 1, 0x06A9 => 1, 0x06AA => 1, 0x06AB => 1, 0x06AC => 1, 0x06AD => 1,
		0x06AE => 1, 0x06AF => 1, 0x06B0 => 1, 0x06B1 => 1, 0x06B2 => 1, 0x06B3 => 1, 0x06B4 => 1, 0x06B5 => 1,
		0x06B6 => 1, 0x06B7 => 1, 0x06B8 => 1, 0x06B9 => 1, 0x06BA => 1, 0x06BB => 1, 0x06BC => 1, 0x06BD => 1,
		0x06BE => 1, 0x06BF => 1, 0x06C0 => 1, 0x06C1 => 1, 0x06C2 => 1, 0x06C3 => 1, 0x06C4 => 1, 0x06C5 => 1,
		0x06C6 => 1, 0x06C7 => 1, 0x06C8 => 1, 0x06C9 => 1, 0x06CA => 1, 0x06CB => 1, 0x06CC => 1, 0x06CD => 1,
		0x06CE => 1, 0x06CF => 1, 0x06D0 => 1, 0x06D1 => 1, 0x06D2 => 1, 0x06D3 => 1, 0x06D5 => 1, 0x06EE => 1,
		0x06EF => 1, 0x06FA => 1, 0x06FB => 1, 0x06FC => 1, 0x06FF => 1, 0x0710 => 1, 0x0712 => 1, 0x0713 => 1,
		0x0714 => 1, 0x0715 => 1, 0x0716 => 1, 0x0717 => 1, 0x0718 => 1, 0x0719 => 1, 0x071A => 1, 0x071B => 1,
		0x071C => 1, 0x071D => 1, 0x071E => 1, 0x071F => 1, 0x0720 => 1, 0x0721 => 1, 0x0722 => 1, 0x0723 => 1,
		0x0724 => 1, 0x0725 => 1, 0x0726 => 1, 0x0727 => 1, 0x0728 => 1, 0x0729 => 1, 0x072A => 1, 0x072B => 1,
		0x072C => 1, 0x072D => 1, 0x072E => 1, 0x072F => 1, 0x074D => 1, 0x074E => 1, 0x074F => 1, 0x0750 => 1,
		0x0751 => 1, 0x0752 => 1, 0x0753 => 1, 0x0754 => 1, 0x0755 => 1, 0x0756 => 1, 0x0757 => 1, 0x0758 => 1,
		0x0759 => 1, 0x075A => 1, 0x075B => 1, 0x075C => 1, 0x075D => 1, 0x075E => 1, 0x075F => 1, 0x0760 => 1,
		0x0761 => 1, 0x0762 => 1, 0x0763 => 1, 0x0764 => 1, 0x0765 => 1, 0x0766 => 1, 0x0767 => 1, 0x0768 => 1,
		0x0769 => 1, 0x076A => 1, 0x076B => 1, 0x076C => 1, 0x076D => 1, 0x076E => 1, 0x076F => 1, 0x0770 => 1,
		0x0771 => 1, 0x0772 => 1, 0x0773 => 1, 0x0774 => 1, 0x0775 => 1, 0x0776 => 1, 0x0777 => 1, 0x0778 => 1,
		0x0779 => 1, 0x077A => 1, 0x077B => 1, 0x077C => 1, 0x077D => 1, 0x077E => 1, 0x077F => 1, 0x07CA => 1,
		0x07CB => 1, 0x07CC => 1, 0x07CD => 1, 0x07CE => 1, 0x07CF => 1, 0x07D0 => 1, 0x07D1 => 1, 0x07D2 => 1,
		0x07D3 => 1, 0x07D4 => 1, 0x07D5 => 1, 0x07D6 => 1, 0x07D7 => 1, 0x07D8 => 1, 0x07D9 => 1, 0x07DA => 1,
		0x07DB => 1, 0x07DC => 1, 0x07DD => 1, 0x07DE => 1, 0x07DF => 1, 0x07E0 => 1, 0x07E1 => 1, 0x07E2 => 1,
		0x07E3 => 1, 0x07E4 => 1, 0x07E5 => 1, 0x07E6 => 1, 0x07E7 => 1, 0x07E8 => 1, 0x07E9 => 1, 0x07EA => 1,
		0x07FA => 1, 0x0840 => 1, 0x0841 => 1, 0x0842 => 1, 0x0843 => 1, 0x0844 => 1, 0x0845 => 1, 0x0846 => 1,
		0x0847 => 1, 0x0848 => 1, 0x0849 => 1, 0x084A => 1, 0x084B => 1, 0x084C => 1, 0x084D => 1, 0x084E => 1,
		0x084F => 1, 0x0850 => 1, 0x0851 => 1, 0x0852 => 1, 0x0853 => 1, 0x0854 => 1, 0x0855 => 1, 0x0856 => 1,
		0x0857 => 1, 0x0858 => 1, 0x0860 => 1, 0x0862 => 1, 0x0863 => 1, 0x0864 => 1, 0x0865 => 1, 0x0867 => 1,
		0x0868 => 1, 0x0869 => 1, 0x086A => 1, 0x0870 => 1, 0x0871 => 1, 0x0872 => 1, 0x0873 => 1, 0x0874 => 1,
		0x0875 => 1, 0x0876 => 1, 0x0877 => 1, 0x0878 => 1, 0x0879 => 1, 0x087A => 1, 0x087B => 1, 0x087C => 1,
		0x087D => 1, 0x087E => 1, 0x087F => 1, 0x0880 => 1, 0x0881 => 1, 0x0882 => 1, 0x0883 => 1, 0x0884 => 1,
		0x0885 => 1, 0x0886 => 1, 0x0889 => 1, 0x088A => 1, 0x088B => 1, 0x088C => 1, 0x088D => 1, 0x088E => 1,
		0x088F => 1, 0x08A0 => 1, 0x08A1 => 1, 0x08A2 => 1, 0x08A3 => 1, 0x08A4 => 1, 0x08A5 => 1, 0x08A6 => 1,
		0x08A7 => 1, 0x08A8 => 1, 0x08A9 => 1, 0x08AA => 1, 0x08AB => 1, 0x08AC => 1, 0x08AE => 1, 0x08AF => 1,
		0x08B0 => 1, 0x08B1 => 1, 0x08B2 => 1, 0x08B3 => 1, 0x08B4 => 1, 0x08B5 => 1, 0x08B6 => 1, 0x08B7 => 1,
		0x08B8 => 1, 0x08B9 => 1, 0x08BA => 1, 0x08BB => 1, 0x08BC => 1, 0x08BD => 1, 0x08BE => 1, 0x08BF => 1,
		0x08C0 => 1, 0x08C1 => 1, 0x08C2 => 1, 0x08C3 => 1, 0x08C4 => 1, 0x08C5 => 1, 0x08C6 => 1, 0x08C7 => 1,
		0x08C8 => 1, 0x200D => 1, 0x10EC2 => 1, 0x10EC3 => 1, 0x10EC4 => 1, 0x10EC6 => 1, 0x10EC7 => 1,
	];

	/* VOWELS = TRANSPARENT-JOINING = Unicode Transparent-Joining type (not just vowels) */
	public static $transparent = [
		0x0610 => 1, 0x0611 => 1, 0x0612 => 1, 0x0613 => 1, 0x0614 => 1, 0x0615 => 1, 0x0616 => 1, 0x0617 => 1,
		0x0618 => 1, 0x0619 => 1, 0x061A => 1, 0x064B => 1, 0x064C => 1, 0x064D => 1, 0x064E => 1, 0x064F => 1,
		0x0650 => 1, 0x0651 => 1, 0x0652 => 1, 0x0653 => 1, 0x0654 => 1, 0x0655 => 1, 0x0656 => 1, 0x0657 => 1,
		0x0658 => 1, 0x0659 => 1, 0x065A => 1, 0x065B => 1, 0x065C => 1, 0x065D => 1, 0x065E => 1, 0x065F => 1,
		0x0670 => 1, 0x06D6 => 1, 0x06D7 => 1, 0x06D8 => 1, 0x06D9 => 1, 0x06DA => 1, 0x06DB => 1, 0x06DC => 1,
		0x06DF => 1, 0x06E0 => 1, 0x06E1 => 1, 0x06E2 => 1, 0x06E3 => 1, 0x06E4 => 1, 0x06E7 => 1, 0x06E8 => 1,
		0x06EA => 1, 0x06EB => 1, 0x06EC => 1, 0x06ED => 1,
		/* Extended Arabic */
		0x08E4 => 1, 0x08E5 => 1, 0x08E6 => 1, 0x08E7 => 1, 0x08E8 => 1, 0x08E9 => 1, 0x08EA => 1, 0x08EB => 1,
		0x08EC => 1, 0x08ED => 1, 0x08EE => 1, 0x08EF => 1, 0x08F0 => 1, 0x08F1 => 1, 0x08F2 => 1, 0x08F3 => 1,
		0x08F4 => 1, 0x08F5 => 1, 0x08F6 => 1, 0x08F7 => 1, 0x08F8 => 1, 0x08F9 => 1, 0x08FA => 1, 0x08FB => 1,
		0x08FC => 1, 0x08FD => 1, 0x08FE => 1,
		/* Arabic ligatures in presentation form (converted in 'ccmp' in e.g. Arial and Times ? need to add others in this range) */
		0xFC5E => 1, 0xFC5F => 1, 0xFC60 => 1, 0xFC61 => 1, 0xFC62 => 1,
		/*  'syrc' Syriac */
		0x070F => 1, 0x0711 => 1, 0x0730 => 1, 0x0731 => 1, 0x0732 => 1, 0x0733 => 1, 0x0734 => 1, 0x0735 => 1,
		0x0736 => 1, 0x0737 => 1, 0x0738 => 1, 0x0739 => 1, 0x073A => 1, 0x073B => 1, 0x073C => 1, 0x073D => 1,
		0x073E => 1, 0x073F => 1, 0x0740 => 1, 0x0741 => 1, 0x0742 => 1, 0x0743 => 1, 0x0744 => 1, 0x0745 => 1,
		0x0746 => 1, 0x0747 => 1, 0x0748 => 1, 0x0749 => 1, 0x074A => 1,
		/* N'Ko */
		0x07EB => 1, 0x07EC => 1, 0x07ED => 1, 0x07EE => 1, 0x07EF => 1, 0x07F0 => 1, 0x07F1 => 1, 0x07F2 => 1,
		0x07F3 => 1,
		/* Mandaic */
		0x0859 => 1, 0x085A => 1, 0x085B => 1,
		];

	/**
	 * The joining group DALATH RISH of ArabicShaping.txt, which with ALAPH is the whole of what the
	 * joining state table reads beyond the joining types. All four letters are right-joining, so an
	 * Alaph after one of them stands apart from it, and fin3 is the form Syriac states for that.
	 */
	private static $dalathRish = [0x0715 => 1, 0x0716 => 1, 0x072A => 1, 0x072F => 1];

	/** The feature each resolved action is stated under, in the order rtlSUB indexes a letter's forms in */
	private static $actionFeatures = ['isol', 'fina', 'init', 'medi', 'med2', 'fin2', 'fin3'];

	/**
	 * Read the form each character of the run calls for out of the joining classes, and write it into
	 * the run as `joining`.
	 *
	 * Read from the characters as written, and so before anything is substituted into the run, because
	 * a substitution can leave a glyph that is no character at all. Where 'ccmp' takes a dotted letter
	 * apart into its rasm and its dots - Noto Sans Arabic does this for beh - the rasm is unencoded,
	 * mPDF has mapped it into the Private Use Area, and a Private Use codepoint is in none of the
	 * joining tables, so the letter would join nothing and neither would its neighbours through it.
	 * HarfBuzz resolves joining in setup_masks() before it applies GSUB for the same reason, and a
	 * glyph a substitution produces carries the mask of the character it came from.
	 *
	 * @param array[] $info            The run, by reference: each character's joining is written into it
	 * @param string  $glyphClassMarks The mark glyphs of GDEF, which join as a vowel does
	 * @param string  $scriptTag       'arab', 'syrc', 'nko ' or 'mand'
	 */
	public static function resolveJoining(&$info, $glyphClassMarks, $scriptTag)
	{
		$transparentJoin = self::transparentJoining($glyphClassMarks);
		$chars = self::hexes($info);

		$nextChar = null;
		for ($i = count($chars) - 1; $i >= 0; $i--) {
			$crntChar = $chars[$i];
			// joining sees the base a mark is written on, however many marks the base carries: behind
			// the position that means walking over them, and in front it means $nextChar, which a
			// transparent-joining character continues without writing
			$n = self::skipTransparent($chars, $i, $transparentJoin);
			$prevChar = isset($chars[$n]) ? hexdec($chars[$n]) : null;
			$joinedToPrevious = $prevChar && isset(self::$leftJoining[$prevChar]);
			$joinedToNext = $nextChar && isset(self::$rightJoining[hexdec($nextChar)]);
			if ($crntChar && isset($transparentJoin[hexdec($crntChar)])) {
				// a transparent-joining character takes a <final> form where letters that join stand
				// either side of it and an <isolated> one otherwise; it never takes a medial or initial
				$info[$i]['joining'] = $joinedToPrevious && $joinedToNext ? 1 : 0;
				continue;
			}
			if (hexdec($crntChar) < 128) {
				$info[$i]['joining'] = 0;
				$nextChar = $crntChar;
				continue;
			}
			if ($scriptTag == 'syrc' && $crntChar == '00710') {
				$action = self::alaphAction($prevChar, $joinedToPrevious, $joinedToNext);
			} else {
				$action = 0;
				if ($joinedToPrevious) {
					$action++;
				}
				if ($joinedToNext) {
					$action += 2;
				}
			}
			$info[$i]['joining'] = $action;
			$nextChar = $crntChar;
		}
	}

	/**
	 * The action the Syriac Alaph U+0710 calls for, read off the ALAPH column of the joining table.
	 *
	 * Syriac states three forms for the Alaph that no other letter has, and HarfBuzz resolves them in
	 * arabic_joining() from the same state table as the other four, letting each state rewrite the
	 * action it has already decided for the character behind it. resolveJoining() decides each
	 * character from its neighbours instead, and for the Alaph the two agree, because every state an
	 * Alaph can be reached in from a given kind of letter holds the same action for it, and the only
	 * rewrites that land on an Alaph - state 4's med2 over a fina and state 5's isol over a fin2 or a
	 * fin3 - both come of a letter that joins backwards following it.
	 *
	 * There is no test here for whether the Alaph ends the word, nor for whether what stands either
	 * side of it is Syriac. HarfBuzz has neither, and reading the joining classes alone is what puts
	 * the Sogdian letters U+074D to U+074F on the same footing as the rest of the block.
	 *
	 * @param int|null $prevChar         The base before the Alaph, past any transparent-joining characters
	 * @param bool     $joinedToPrevious Whether that base is one that joins to what follows it
	 * @param bool     $joinedToNext     Whether the base after the Alaph joins to what precedes it
	 *
	 * @return int 0=ISOL, 1=FINA, 4=MED2, 5=FIN2, 6=FIN3
	 */
	private static function alaphAction($prevChar, $joinedToPrevious, $joinedToNext)
	{
		if ($joinedToPrevious) {
			return $joinedToNext ? 4 : 1;
		}

		// nothing stands before the Alaph for it to be drawn apart from, or a letter follows it that
		// joins back over the form the Alaph would otherwise have taken
		if ($joinedToNext || $prevChar === null || !isset(self::$rightJoining[$prevChar])) {
			return 0;
		}

		return isset(self::$dalathRish[$prevChar]) ? 6 : 5;
	}

	/**
	 * Put every character of the run into the form resolveJoining() said its joining calls for.
	 *
	 * A form is usually one glyph and is written straight into $info. It need not be: a font may state
	 * one as a base glyph and the marks drawn on it, which is how the Nastaliq faces write their
	 * initial and medial forms. One character is then several glyphs, and making a run longer is the
	 * caller's to do - it holds the ligature and mark bookkeeping that a change in length disturbs -
	 * so such a form is handed back whole for the caller to substitute.
	 *
	 * @param array[] $info       The run, by reference: the form substituted is written into it
	 * @param array   $arabGlyphs The font's rtlSUB table: the glyph for each form of each letter
	 * @param string  $usetags    Which of the form features the document left switched on
	 *
	 * @return int[][] The forms of more than one glyph, as the code points to put in the character's
	 *                 place, keyed by the position in $info it has
	 */
	public static function shape(&$info, $arabGlyphs, $usetags)
	{
		$chars = self::hexes($info);

		$multiple = [];
		for ($i = 0; $i < count($chars); $i++) {
			list($substitute, $form) = self::glyphs($chars[$i], $info[$i]['joining'], $chars, $i, $usetags, $arabGlyphs);

			// rtlSUB writes a form of several glyphs as one space-separated string, which hexdec()
			// would read as a single code point
			$glyphs = explode(' ', $substitute);

			$info[$i]['uni'] = hexdec($glyphs[0]);
			$info[$i]['hex'] = $glyphs[0];
			$info[$i]['form'] = $form; // Actaul form substituted 0=ISOLATED FORM :: 1=FINAL :: 2=INITIAL :: 3=MEDIAL

			if (count($glyphs) > 1) {
				$multiple[$i] = array_map('hexdec', $glyphs);
			}
		}

		return $multiple;
	}

	/**
	 * The run as hex code points, which is what joining and the context rules are matched against.
	 *
	 * Read once either side of the substitutions that stand between resolveJoining() and shape(), so
	 * the two need not be the same run: 'ccmp' may have made it longer.
	 */
	private static function hexes($info)
	{
		$chars = [];
		for ($i = 0; $i < count($info); $i++) {
			$chars[] = $info[$i]['hex'];
		}

		return $chars;
	}

	/**
	 * The Transparent-Joining table for this string.
	 *
	 * A GDEF mark is transparent to joining just as a vowel is, so the mark class joins the table.
	 * Array + keeps the left operand on collision, so a codepoint in both stays as the Unicode table
	 * has it.
	 */
	private static function transparentJoining($glyphClassMarks)
	{
		$gcm = [];
		foreach (explode('| ', $glyphClassMarks) as $g) {
			$gcm[hexdec($g)] = 1;
		}

		return self::$transparent + $gcm;
	}

	/**
	 * The position behind $i that joining sees, which is the first one past any transparent-joining
	 * characters.
	 *
	 * @param array $chars           The run, as hex code points
	 * @param int   $i               The position to walk back from
	 * @param array $transparentJoin The Transparent-Joining table, with GDEF's marks
	 *
	 * @return int The position reached, which the run need not hold
	 */
	private static function skipTransparent(&$chars, $i, $transparentJoin)
	{
		$n = $i - 1;
		while (isset($chars[$n]) && isset($transparentJoin[hexdec($chars[$n])])) {
			$n--;
		}

		return $n;
	}

	private static function glyphs($char, $action, &$chars, $i, $usetags, $arabGlyphs)
	{
		// A form whose feature the document switched off through OTLtags is not substituted, Syriac's
		// three extra forms included
		if (strpos($usetags, self::$actionFeatures[$action]) === false) {
			return [$char, 0];
		}

		if (isset($arabGlyphs[$char][$action])) {
			$retk = $action;
		} elseif ($action == 3 && isset($arabGlyphs[$char][1])) { // if <medial> not defined, but <final>, return <final>
			$retk = 1;
		} elseif ($action == 2 && isset($arabGlyphs[$char][0])) { // if <initial> not defined, but <isolated>, return <isolated>
			$retk = 0;
		} else {
			return [$char, 0];
		}

		$match = true;
		// If GSUB includes a Backtrack or Lookahead condition (e.g. font ArabicTypesetting)
		// The walk over ignored glyphs stops at the edge of the run, and a position it runs out before
		// reaching is not held, as in HarfBuzz's match_backtrack() and match_lookahead(). Past the edge
		// the glyph is null, which inList() finds in any pattern from PHP 8, so the walk would not end.
		if (isset($arabGlyphs[$char]['prel'][$retk]) && $arabGlyphs[$char]['prel'][$retk]) {
			$ig = 1;
			foreach ($arabGlyphs[$char]['prel'][$retk] as $k => $v) { // $k starts 0, 1...
				if (!isset($chars[$i - $ig - $k])) {
					$match = false;
				} elseif (!GlyphString::inList($v, $chars[$i - $ig - $k])) {
					while (isset($chars[$i - $ig - $k]) && GlyphString::inList($arabGlyphs[$char]['ignore'][$retk], $chars[$i - $ig - $k])) {
						$ig++;
					}
					if (!isset($chars[$i - $ig - $k])) {
						$match = false;
					} elseif (!GlyphString::inList($v, $chars[$i - $ig - $k])) {
						$match = false;
					}
				}
			}
		}
		if (isset($arabGlyphs[$char]['postl'][$retk]) && $arabGlyphs[$char]['postl'][$retk]) {
			$ig = 1;
			foreach ($arabGlyphs[$char]['postl'][$retk] as $k => $v) { // $k starts 0, 1...
				if (!isset($chars[$i + $ig + $k])) {
					$match = false;
				} elseif (!GlyphString::inList($v, $chars[$i + $ig + $k])) {
					while (isset($chars[$i + $ig + $k]) && GlyphString::inList($arabGlyphs[$char]['ignore'][$retk], $chars[$i + $ig + $k])) {
						$ig++;
					}
					if (!isset($chars[$i + $ig + $k])) {
						$match = false;
					} elseif (!GlyphString::inList($v, $chars[$i + $ig + $k])) {
						$match = false;
					}
				}
			}
		}

		return $match ? [$arabGlyphs[$char][$retk], $retk] : [$char, 0];
	}
}
