<?php

namespace Mpdf\Shaper;

use Mpdf\Fonts\GlyphString;

/**
 * Arabic and Syriac cursive joining.
 *
 * Every other script reaches its positional forms through GSUB: the font carries isol/fina/medi/init
 * lookups and Otl applies them like any other feature. Arabic and Syriac do not - mPDF resolves the
 * form here from the Unicode joining classes, then substitutes the glyph the font's rtlSUB table
 * names for it. So this stands in place of those four features rather than alongside them, and of the
 * fin2/fin3/med2 Syriac adds for the Alaph.
 *
 * @see https://unicode.org/Public/UNIDATA/ArabicShaping.txt
 * @see https://unicode.org/Public/UNIDATA/extracted/DerivedJoiningType.txt
 */
class Arabic
{

	// UNIDATA_VERSION 18.0.0
	/**
	 * The characters that join to the letter written after them, which is what an initial or a medial
	 * form is drawn for: Unicode's Left-Joining, Dual-Joining and Join_Causing types.
	 *
	 * This and $rightJoining are generated by composer arabicjoining:update from the Joining_Type
	 * property - see tests/Mpdf/ArabicJoining.php. Missing from either table, a character joins nothing
	 * and unjoins its neighbour, so a list that falls behind Unicode draws the letter before a character
	 * newer than itself with no form at all, which is what hand-maintaining these cost (#251).
	 */
	public static $leftJoining = [
		0x0620 => 1, 0x0626 => 1, 0x0628 => 1, 0x062A => 1, 0x062B => 1, 0x062C => 1, 0x062D => 1, 0x062E => 1,
		0x0633 => 1, 0x0634 => 1, 0x0635 => 1, 0x0636 => 1, 0x0637 => 1, 0x0638 => 1, 0x0639 => 1, 0x063A => 1,
		0x063B => 1, 0x063C => 1, 0x063D => 1, 0x063E => 1, 0x063F => 1, 0x0640 => 1, 0x0641 => 1, 0x0642 => 1,
		0x0643 => 1, 0x0644 => 1, 0x0645 => 1, 0x0646 => 1, 0x0647 => 1, 0x0649 => 1, 0x064A => 1, 0x066E => 1,
		0x066F => 1, 0x0678 => 1, 0x0679 => 1, 0x067A => 1, 0x067B => 1, 0x067C => 1, 0x067D => 1, 0x067E => 1,
		0x067F => 1, 0x0680 => 1, 0x0681 => 1, 0x0682 => 1, 0x0683 => 1, 0x0684 => 1, 0x0685 => 1, 0x0686 => 1,
		0x0687 => 1, 0x069A => 1, 0x069B => 1, 0x069C => 1, 0x069D => 1, 0x069E => 1, 0x069F => 1, 0x06A0 => 1,
		0x06A1 => 1, 0x06A2 => 1, 0x06A3 => 1, 0x06A4 => 1, 0x06A5 => 1, 0x06A6 => 1, 0x06A7 => 1, 0x06A8 => 1,
		0x06A9 => 1, 0x06AA => 1, 0x06AB => 1, 0x06AC => 1, 0x06AD => 1, 0x06AE => 1, 0x06AF => 1, 0x06B0 => 1,
		0x06B1 => 1, 0x06B2 => 1, 0x06B3 => 1, 0x06B4 => 1, 0x06B5 => 1, 0x06B6 => 1, 0x06B7 => 1, 0x06B8 => 1,
		0x06B9 => 1, 0x06BA => 1, 0x06BB => 1, 0x06BC => 1, 0x06BD => 1, 0x06BE => 1, 0x06BF => 1, 0x06C1 => 1,
		0x06C2 => 1, 0x06CC => 1, 0x06CE => 1, 0x06D0 => 1, 0x06D1 => 1, 0x06FA => 1, 0x06FB => 1, 0x06FC => 1,
		0x06FF => 1, 0x0712 => 1, 0x0713 => 1, 0x0714 => 1, 0x071A => 1, 0x071B => 1, 0x071C => 1, 0x071D => 1,
		0x071F => 1, 0x0720 => 1, 0x0721 => 1, 0x0722 => 1, 0x0723 => 1, 0x0724 => 1, 0x0725 => 1, 0x0726 => 1,
		0x0727 => 1, 0x0729 => 1, 0x072B => 1, 0x072D => 1, 0x072E => 1, 0x074E => 1, 0x074F => 1, 0x0750 => 1,
		0x0751 => 1, 0x0752 => 1, 0x0753 => 1, 0x0754 => 1, 0x0755 => 1, 0x0756 => 1, 0x0757 => 1, 0x0758 => 1,
		0x075C => 1, 0x075D => 1, 0x075E => 1, 0x075F => 1, 0x0760 => 1, 0x0761 => 1, 0x0762 => 1, 0x0763 => 1,
		0x0764 => 1, 0x0765 => 1, 0x0766 => 1, 0x0767 => 1, 0x0768 => 1, 0x0769 => 1, 0x076A => 1, 0x076D => 1,
		0x076E => 1, 0x076F => 1, 0x0770 => 1, 0x0772 => 1, 0x0775 => 1, 0x0776 => 1, 0x0777 => 1, 0x077A => 1,
		0x077B => 1, 0x077C => 1, 0x077D => 1, 0x077E => 1, 0x077F => 1, 0x07CA => 1, 0x07CB => 1, 0x07CC => 1,
		0x07CD => 1, 0x07CE => 1, 0x07CF => 1, 0x07D0 => 1, 0x07D1 => 1, 0x07D2 => 1, 0x07D3 => 1, 0x07D4 => 1,
		0x07D5 => 1, 0x07D6 => 1, 0x07D7 => 1, 0x07D8 => 1, 0x07D9 => 1, 0x07DA => 1, 0x07DB => 1, 0x07DC => 1,
		0x07DD => 1, 0x07DE => 1, 0x07DF => 1, 0x07E0 => 1, 0x07E1 => 1, 0x07E2 => 1, 0x07E3 => 1, 0x07E4 => 1,
		0x07E5 => 1, 0x07E6 => 1, 0x07E7 => 1, 0x07E8 => 1, 0x07E9 => 1, 0x07EA => 1, 0x07FA => 1, 0x0841 => 1,
		0x0842 => 1, 0x0843 => 1, 0x0844 => 1, 0x0845 => 1, 0x0848 => 1, 0x084A => 1, 0x084B => 1, 0x084C => 1,
		0x084D => 1, 0x084E => 1, 0x084F => 1, 0x0850 => 1, 0x0851 => 1, 0x0852 => 1, 0x0853 => 1, 0x0855 => 1,
		0x0860 => 1, 0x0862 => 1, 0x0863 => 1, 0x0864 => 1, 0x0865 => 1, 0x0868 => 1, 0x0883 => 1, 0x0884 => 1,
		0x0885 => 1, 0x0886 => 1, 0x0889 => 1, 0x088A => 1, 0x088B => 1, 0x088C => 1, 0x088D => 1, 0x088F => 1,
		0x08A0 => 1, 0x08A1 => 1, 0x08A2 => 1, 0x08A3 => 1, 0x08A4 => 1, 0x08A5 => 1, 0x08A6 => 1, 0x08A7 => 1,
		0x08A8 => 1, 0x08A9 => 1, 0x08AF => 1, 0x08B0 => 1, 0x08B3 => 1, 0x08B4 => 1, 0x08B5 => 1, 0x08B6 => 1,
		0x08B7 => 1, 0x08B8 => 1, 0x08BA => 1, 0x08BB => 1, 0x08BC => 1, 0x08BD => 1, 0x08BE => 1, 0x08BF => 1,
		0x08C0 => 1, 0x08C1 => 1, 0x08C2 => 1, 0x08C3 => 1, 0x08C4 => 1, 0x08C5 => 1, 0x08C6 => 1, 0x08C7 => 1,
		0x08C8 => 1, 0x200D => 1, 0x10EC3 => 1, 0x10EC4 => 1, 0x10EC6 => 1, 0x10EC7 => 1, 0x10ED9 => 1, 0x10EDA => 1,
		0x10EDB => 1, 0x10EDC => 1, 0x10EDD => 1, 0x10EDE => 1, 0x10EDF => 1, 0x10EE0 => 1, 0x10EE1 => 1, 0x10EE2 => 1,
		0x10EE3 => 1, 0x10EE4 => 1, 0x10EE5 => 1, 0x10EE6 => 1, 0x10EE7 => 1, 0x10EE8 => 1, 0x10EE9 => 1, 0x10EEA => 1,
		0x10EEB => 1, 0x10EEC => 1, 0x10EED => 1, 0x10EEE => 1,
	];

	/**
	 * The characters that join to the letter written before them, which is what a final or a medial form
	 * is drawn for: Unicode's Right-Joining, Dual-Joining and Join_Causing types.
	 */
	public static $rightJoining = [
		0x0620 => 1, 0x0622 => 1, 0x0623 => 1, 0x0624 => 1, 0x0625 => 1, 0x0626 => 1, 0x0627 => 1, 0x0628 => 1,
		0x0629 => 1, 0x062A => 1, 0x062B => 1, 0x062C => 1, 0x062D => 1, 0x062E => 1, 0x062F => 1, 0x0630 => 1,
		0x0631 => 1, 0x0632 => 1, 0x0633 => 1, 0x0634 => 1, 0x0635 => 1, 0x0636 => 1, 0x0637 => 1, 0x0638 => 1,
		0x0639 => 1, 0x063A => 1, 0x063B => 1, 0x063C => 1, 0x063D => 1, 0x063E => 1, 0x063F => 1, 0x0640 => 1,
		0x0641 => 1, 0x0642 => 1, 0x0643 => 1, 0x0644 => 1, 0x0645 => 1, 0x0646 => 1, 0x0647 => 1, 0x0648 => 1,
		0x0649 => 1, 0x064A => 1, 0x066E => 1, 0x066F => 1, 0x0671 => 1, 0x0672 => 1, 0x0673 => 1, 0x0675 => 1,
		0x0676 => 1, 0x0677 => 1, 0x0678 => 1, 0x0679 => 1, 0x067A => 1, 0x067B => 1, 0x067C => 1, 0x067D => 1,
		0x067E => 1, 0x067F => 1, 0x0680 => 1, 0x0681 => 1, 0x0682 => 1, 0x0683 => 1, 0x0684 => 1, 0x0685 => 1,
		0x0686 => 1, 0x0687 => 1, 0x0688 => 1, 0x0689 => 1, 0x068A => 1, 0x068B => 1, 0x068C => 1, 0x068D => 1,
		0x068E => 1, 0x068F => 1, 0x0690 => 1, 0x0691 => 1, 0x0692 => 1, 0x0693 => 1, 0x0694 => 1, 0x0695 => 1,
		0x0696 => 1, 0x0697 => 1, 0x0698 => 1, 0x0699 => 1, 0x069A => 1, 0x069B => 1, 0x069C => 1, 0x069D => 1,
		0x069E => 1, 0x069F => 1, 0x06A0 => 1, 0x06A1 => 1, 0x06A2 => 1, 0x06A3 => 1, 0x06A4 => 1, 0x06A5 => 1,
		0x06A6 => 1, 0x06A7 => 1, 0x06A8 => 1, 0x06A9 => 1, 0x06AA => 1, 0x06AB => 1, 0x06AC => 1, 0x06AD => 1,
		0x06AE => 1, 0x06AF => 1, 0x06B0 => 1, 0x06B1 => 1, 0x06B2 => 1, 0x06B3 => 1, 0x06B4 => 1, 0x06B5 => 1,
		0x06B6 => 1, 0x06B7 => 1, 0x06B8 => 1, 0x06B9 => 1, 0x06BA => 1, 0x06BB => 1, 0x06BC => 1, 0x06BD => 1,
		0x06BE => 1, 0x06BF => 1, 0x06C0 => 1, 0x06C1 => 1, 0x06C2 => 1, 0x06C3 => 1, 0x06C4 => 1, 0x06C5 => 1,
		0x06C6 => 1, 0x06C7 => 1, 0x06C8 => 1, 0x06C9 => 1, 0x06CA => 1, 0x06CB => 1, 0x06CC => 1, 0x06CD => 1,
		0x06CE => 1, 0x06CF => 1, 0x06D0 => 1, 0x06D1 => 1, 0x06D2 => 1, 0x06D3 => 1, 0x06D5 => 1, 0x06EE => 1,
		0x06EF => 1, 0x06FA => 1, 0x06FB => 1, 0x06FC => 1, 0x06FF => 1, 0x0710 => 1, 0x0712 => 1, 0x0713 => 1,
		0x0714 => 1, 0x0715 => 1, 0x0716 => 1, 0x0717 => 1, 0x0718 => 1, 0x0719 => 1, 0x071A => 1, 0x071B => 1,
		0x071C => 1, 0x071D => 1, 0x071E => 1, 0x071F => 1, 0x0720 => 1, 0x0721 => 1, 0x0722 => 1, 0x0723 => 1,
		0x0724 => 1, 0x0725 => 1, 0x0726 => 1, 0x0727 => 1, 0x0728 => 1, 0x0729 => 1, 0x072A => 1, 0x072B => 1,
		0x072C => 1, 0x072D => 1, 0x072E => 1, 0x072F => 1, 0x074D => 1, 0x074E => 1, 0x074F => 1, 0x0750 => 1,
		0x0751 => 1, 0x0752 => 1, 0x0753 => 1, 0x0754 => 1, 0x0755 => 1, 0x0756 => 1, 0x0757 => 1, 0x0758 => 1,
		0x0759 => 1, 0x075A => 1, 0x075B => 1, 0x075C => 1, 0x075D => 1, 0x075E => 1, 0x075F => 1, 0x0760 => 1,
		0x0761 => 1, 0x0762 => 1, 0x0763 => 1, 0x0764 => 1, 0x0765 => 1, 0x0766 => 1, 0x0767 => 1, 0x0768 => 1,
		0x0769 => 1, 0x076A => 1, 0x076B => 1, 0x076C => 1, 0x076D => 1, 0x076E => 1, 0x076F => 1, 0x0770 => 1,
		0x0771 => 1, 0x0772 => 1, 0x0773 => 1, 0x0774 => 1, 0x0775 => 1, 0x0776 => 1, 0x0777 => 1, 0x0778 => 1,
		0x0779 => 1, 0x077A => 1, 0x077B => 1, 0x077C => 1, 0x077D => 1, 0x077E => 1, 0x077F => 1, 0x07CA => 1,
		0x07CB => 1, 0x07CC => 1, 0x07CD => 1, 0x07CE => 1, 0x07CF => 1, 0x07D0 => 1, 0x07D1 => 1, 0x07D2 => 1,
		0x07D3 => 1, 0x07D4 => 1, 0x07D5 => 1, 0x07D6 => 1, 0x07D7 => 1, 0x07D8 => 1, 0x07D9 => 1, 0x07DA => 1,
		0x07DB => 1, 0x07DC => 1, 0x07DD => 1, 0x07DE => 1, 0x07DF => 1, 0x07E0 => 1, 0x07E1 => 1, 0x07E2 => 1,
		0x07E3 => 1, 0x07E4 => 1, 0x07E5 => 1, 0x07E6 => 1, 0x07E7 => 1, 0x07E8 => 1, 0x07E9 => 1, 0x07EA => 1,
		0x07FA => 1, 0x0840 => 1, 0x0841 => 1, 0x0842 => 1, 0x0843 => 1, 0x0844 => 1, 0x0845 => 1, 0x0846 => 1,
		0x0847 => 1, 0x0848 => 1, 0x0849 => 1, 0x084A => 1, 0x084B => 1, 0x084C => 1, 0x084D => 1, 0x084E => 1,
		0x084F => 1, 0x0850 => 1, 0x0851 => 1, 0x0852 => 1, 0x0853 => 1, 0x0854 => 1, 0x0855 => 1, 0x0856 => 1,
		0x0857 => 1, 0x0858 => 1, 0x0860 => 1, 0x0862 => 1, 0x0863 => 1, 0x0864 => 1, 0x0865 => 1, 0x0867 => 1,
		0x0868 => 1, 0x0869 => 1, 0x086A => 1, 0x0870 => 1, 0x0871 => 1, 0x0872 => 1, 0x0873 => 1, 0x0874 => 1,
		0x0875 => 1, 0x0876 => 1, 0x0877 => 1, 0x0878 => 1, 0x0879 => 1, 0x087A => 1, 0x087B => 1, 0x087C => 1,
		0x087D => 1, 0x087E => 1, 0x087F => 1, 0x0880 => 1, 0x0881 => 1, 0x0882 => 1, 0x0883 => 1, 0x0884 => 1,
		0x0885 => 1, 0x0886 => 1, 0x0889 => 1, 0x088A => 1, 0x088B => 1, 0x088C => 1, 0x088D => 1, 0x088E => 1,
		0x088F => 1, 0x08A0 => 1, 0x08A1 => 1, 0x08A2 => 1, 0x08A3 => 1, 0x08A4 => 1, 0x08A5 => 1, 0x08A6 => 1,
		0x08A7 => 1, 0x08A8 => 1, 0x08A9 => 1, 0x08AA => 1, 0x08AB => 1, 0x08AC => 1, 0x08AE => 1, 0x08AF => 1,
		0x08B0 => 1, 0x08B1 => 1, 0x08B2 => 1, 0x08B3 => 1, 0x08B4 => 1, 0x08B5 => 1, 0x08B6 => 1, 0x08B7 => 1,
		0x08B8 => 1, 0x08B9 => 1, 0x08BA => 1, 0x08BB => 1, 0x08BC => 1, 0x08BD => 1, 0x08BE => 1, 0x08BF => 1,
		0x08C0 => 1, 0x08C1 => 1, 0x08C2 => 1, 0x08C3 => 1, 0x08C4 => 1, 0x08C5 => 1, 0x08C6 => 1, 0x08C7 => 1,
		0x08C8 => 1, 0x200D => 1, 0x10EC2 => 1, 0x10EC3 => 1, 0x10EC4 => 1, 0x10EC6 => 1, 0x10EC7 => 1,
	];

	/**
	 * The characters joining reads straight over, so that the letters either side of one see each other:
	 * Unicode's Transparent-Joining type, which is the marks and the invisible format characters rather
	 * than just the vowels this table was once named for.
	 *
	 * Generated alongside the two above, from extracted/DerivedJoiningType.txt - ArabicShaping.txt leaves
	 * the type to be derived and says so. Missing from here, a character is read as a base, takes a form
	 * of its own and breaks the join across itself; a font that has the mark files it in GDEF and hides
	 * that, so the defect was exactly the fonts with no glyph for it (#259).
	 */
	public static $transparent = [
		0x00AD => 1, 0x0300 => 1, 0x0301 => 1, 0x0302 => 1, 0x0303 => 1, 0x0304 => 1, 0x0305 => 1, 0x0306 => 1,
		0x0307 => 1, 0x0308 => 1, 0x0309 => 1, 0x030A => 1, 0x030B => 1, 0x030C => 1, 0x030D => 1, 0x030E => 1,
		0x030F => 1, 0x0310 => 1, 0x0311 => 1, 0x0312 => 1, 0x0313 => 1, 0x0314 => 1, 0x0315 => 1, 0x0316 => 1,
		0x0317 => 1, 0x0318 => 1, 0x0319 => 1, 0x031A => 1, 0x031B => 1, 0x031C => 1, 0x031D => 1, 0x031E => 1,
		0x031F => 1, 0x0320 => 1, 0x0321 => 1, 0x0322 => 1, 0x0323 => 1, 0x0324 => 1, 0x0325 => 1, 0x0326 => 1,
		0x0327 => 1, 0x0328 => 1, 0x0329 => 1, 0x032A => 1, 0x032B => 1, 0x032C => 1, 0x032D => 1, 0x032E => 1,
		0x032F => 1, 0x0330 => 1, 0x0331 => 1, 0x0332 => 1, 0x0333 => 1, 0x0334 => 1, 0x0335 => 1, 0x0336 => 1,
		0x0337 => 1, 0x0338 => 1, 0x0339 => 1, 0x033A => 1, 0x033B => 1, 0x033C => 1, 0x033D => 1, 0x033E => 1,
		0x033F => 1, 0x0340 => 1, 0x0341 => 1, 0x0342 => 1, 0x0343 => 1, 0x0344 => 1, 0x0345 => 1, 0x0346 => 1,
		0x0347 => 1, 0x0348 => 1, 0x0349 => 1, 0x034A => 1, 0x034B => 1, 0x034C => 1, 0x034D => 1, 0x034E => 1,
		0x034F => 1, 0x0350 => 1, 0x0351 => 1, 0x0352 => 1, 0x0353 => 1, 0x0354 => 1, 0x0355 => 1, 0x0356 => 1,
		0x0357 => 1, 0x0358 => 1, 0x0359 => 1, 0x035A => 1, 0x035B => 1, 0x035C => 1, 0x035D => 1, 0x035E => 1,
		0x035F => 1, 0x0360 => 1, 0x0361 => 1, 0x0362 => 1, 0x0363 => 1, 0x0364 => 1, 0x0365 => 1, 0x0366 => 1,
		0x0367 => 1, 0x0368 => 1, 0x0369 => 1, 0x036A => 1, 0x036B => 1, 0x036C => 1, 0x036D => 1, 0x036E => 1,
		0x036F => 1, 0x0485 => 1, 0x0486 => 1, 0x0610 => 1, 0x0611 => 1, 0x0612 => 1, 0x0613 => 1, 0x0614 => 1,
		0x0615 => 1, 0x0616 => 1, 0x0617 => 1, 0x0618 => 1, 0x0619 => 1, 0x061A => 1, 0x061C => 1, 0x064B => 1,
		0x064C => 1, 0x064D => 1, 0x064E => 1, 0x064F => 1, 0x0650 => 1, 0x0651 => 1, 0x0652 => 1, 0x0653 => 1,
		0x0654 => 1, 0x0655 => 1, 0x0656 => 1, 0x0657 => 1, 0x0658 => 1, 0x0659 => 1, 0x065A => 1, 0x065B => 1,
		0x065C => 1, 0x065D => 1, 0x065E => 1, 0x065F => 1, 0x0670 => 1, 0x06D6 => 1, 0x06D7 => 1, 0x06D8 => 1,
		0x06D9 => 1, 0x06DA => 1, 0x06DB => 1, 0x06DC => 1, 0x06DF => 1, 0x06E0 => 1, 0x06E1 => 1, 0x06E2 => 1,
		0x06E3 => 1, 0x06E4 => 1, 0x06E7 => 1, 0x06E8 => 1, 0x06EA => 1, 0x06EB => 1, 0x06EC => 1, 0x06ED => 1,
		0x070F => 1, 0x0711 => 1, 0x0730 => 1, 0x0731 => 1, 0x0732 => 1, 0x0733 => 1, 0x0734 => 1, 0x0735 => 1,
		0x0736 => 1, 0x0737 => 1, 0x0738 => 1, 0x0739 => 1, 0x073A => 1, 0x073B => 1, 0x073C => 1, 0x073D => 1,
		0x073E => 1, 0x073F => 1, 0x0740 => 1, 0x0741 => 1, 0x0742 => 1, 0x0743 => 1, 0x0744 => 1, 0x0745 => 1,
		0x0746 => 1, 0x0747 => 1, 0x0748 => 1, 0x0749 => 1, 0x074A => 1, 0x07EB => 1, 0x07EC => 1, 0x07ED => 1,
		0x07EE => 1, 0x07EF => 1, 0x07F0 => 1, 0x07F1 => 1, 0x07F2 => 1, 0x07F3 => 1, 0x07FD => 1, 0x0859 => 1,
		0x085A => 1, 0x085B => 1, 0x0897 => 1, 0x0898 => 1, 0x0899 => 1, 0x089A => 1, 0x089B => 1, 0x089C => 1,
		0x089D => 1, 0x089E => 1, 0x089F => 1, 0x08CA => 1, 0x08CB => 1, 0x08CC => 1, 0x08CD => 1, 0x08CE => 1,
		0x08CF => 1, 0x08D0 => 1, 0x08D1 => 1, 0x08D2 => 1, 0x08D3 => 1, 0x08D4 => 1, 0x08D5 => 1, 0x08D6 => 1,
		0x08D7 => 1, 0x08D8 => 1, 0x08D9 => 1, 0x08DA => 1, 0x08DB => 1, 0x08DC => 1, 0x08DD => 1, 0x08DE => 1,
		0x08DF => 1, 0x08E0 => 1, 0x08E1 => 1, 0x08E3 => 1, 0x08E4 => 1, 0x08E5 => 1, 0x08E6 => 1, 0x08E7 => 1,
		0x08E8 => 1, 0x08E9 => 1, 0x08EA => 1, 0x08EB => 1, 0x08EC => 1, 0x08ED => 1, 0x08EE => 1, 0x08EF => 1,
		0x08F0 => 1, 0x08F1 => 1, 0x08F2 => 1, 0x08F3 => 1, 0x08F4 => 1, 0x08F5 => 1, 0x08F6 => 1, 0x08F7 => 1,
		0x08F8 => 1, 0x08F9 => 1, 0x08FA => 1, 0x08FB => 1, 0x08FC => 1, 0x08FD => 1, 0x08FE => 1, 0x08FF => 1,
		0x0951 => 1, 0x0952 => 1, 0x0953 => 1, 0x0954 => 1, 0x1AB0 => 1, 0x1AB1 => 1, 0x1AB2 => 1, 0x1AB3 => 1,
		0x1AB4 => 1, 0x1AB5 => 1, 0x1AB6 => 1, 0x1AB7 => 1, 0x1AB8 => 1, 0x1AB9 => 1, 0x1ABA => 1, 0x1ABB => 1,
		0x1ABC => 1, 0x1ABD => 1, 0x1ABE => 1, 0x1ABF => 1, 0x1AC0 => 1, 0x1AC1 => 1, 0x1AC2 => 1, 0x1AC3 => 1,
		0x1AC4 => 1, 0x1AC5 => 1, 0x1AC6 => 1, 0x1AC7 => 1, 0x1AC8 => 1, 0x1AC9 => 1, 0x1ACA => 1, 0x1ACB => 1,
		0x1ACC => 1, 0x1ACD => 1, 0x1ACE => 1, 0x1ACF => 1, 0x1AD0 => 1, 0x1AD1 => 1, 0x1AD2 => 1, 0x1AD3 => 1,
		0x1AD4 => 1, 0x1AD5 => 1, 0x1AD6 => 1, 0x1AD7 => 1, 0x1AD8 => 1, 0x1AD9 => 1, 0x1ADA => 1, 0x1ADB => 1,
		0x1ADC => 1, 0x1ADD => 1, 0x1ADE => 1, 0x1ADF => 1, 0x1AE0 => 1, 0x1AE1 => 1, 0x1AE2 => 1, 0x1AE3 => 1,
		0x1AE4 => 1, 0x1AE5 => 1, 0x1AE6 => 1, 0x1AE7 => 1, 0x1AE8 => 1, 0x1AE9 => 1, 0x1AEA => 1, 0x1AEB => 1,
		0x1AEC => 1, 0x1AED => 1, 0x1AEE => 1, 0x1AEF => 1, 0x1AF0 => 1, 0x1CD0 => 1, 0x1CD1 => 1, 0x1CD2 => 1,
		0x1CD4 => 1, 0x1CD5 => 1, 0x1CD6 => 1, 0x1CD7 => 1, 0x1CD8 => 1, 0x1CD9 => 1, 0x1CDA => 1, 0x1CDB => 1,
		0x1CDC => 1, 0x1CDD => 1, 0x1CDE => 1, 0x1CDF => 1, 0x1CE0 => 1, 0x1CE2 => 1, 0x1CE3 => 1, 0x1CE4 => 1,
		0x1CE5 => 1, 0x1CE6 => 1, 0x1CE7 => 1, 0x1CE8 => 1, 0x1CED => 1, 0x1CF4 => 1, 0x1CF8 => 1, 0x1CF9 => 1,
		0x1DC0 => 1, 0x1DC1 => 1, 0x1DC2 => 1, 0x1DC3 => 1, 0x1DC4 => 1, 0x1DC5 => 1, 0x1DC6 => 1, 0x1DC7 => 1,
		0x1DC8 => 1, 0x1DC9 => 1, 0x1DCA => 1, 0x1DCB => 1, 0x1DCC => 1, 0x1DCD => 1, 0x1DCE => 1, 0x1DCF => 1,
		0x1DD0 => 1, 0x1DD1 => 1, 0x1DD2 => 1, 0x1DD3 => 1, 0x1DD4 => 1, 0x1DD5 => 1, 0x1DD6 => 1, 0x1DD7 => 1,
		0x1DD8 => 1, 0x1DD9 => 1, 0x1DDA => 1, 0x1DDB => 1, 0x1DDC => 1, 0x1DDD => 1, 0x1DDE => 1, 0x1DDF => 1,
		0x1DE0 => 1, 0x1DE1 => 1, 0x1DE2 => 1, 0x1DE3 => 1, 0x1DE4 => 1, 0x1DE5 => 1, 0x1DE6 => 1, 0x1DE7 => 1,
		0x1DE8 => 1, 0x1DE9 => 1, 0x1DEA => 1, 0x1DEB => 1, 0x1DEC => 1, 0x1DED => 1, 0x1DEE => 1, 0x1DEF => 1,
		0x1DF0 => 1, 0x1DF1 => 1, 0x1DF2 => 1, 0x1DF3 => 1, 0x1DF4 => 1, 0x1DF5 => 1, 0x1DF6 => 1, 0x1DF7 => 1,
		0x1DF8 => 1, 0x1DF9 => 1, 0x1DFA => 1, 0x1DFB => 1, 0x1DFC => 1, 0x1DFD => 1, 0x1DFE => 1, 0x1DFF => 1,
		0x200B => 1, 0x200E => 1, 0x200F => 1, 0x202A => 1, 0x202B => 1, 0x202C => 1, 0x202D => 1, 0x202E => 1,
		0x2060 => 1, 0x2061 => 1, 0x2062 => 1, 0x2063 => 1, 0x2064 => 1, 0x206A => 1, 0x206B => 1, 0x206C => 1,
		0x206D => 1, 0x206E => 1, 0x206F => 1, 0x20D0 => 1, 0x20D1 => 1, 0x20D2 => 1, 0x20D3 => 1, 0x20D4 => 1,
		0x20D5 => 1, 0x20D6 => 1, 0x20D7 => 1, 0x20D8 => 1, 0x20D9 => 1, 0x20DA => 1, 0x20DB => 1, 0x20DC => 1,
		0x20DD => 1, 0x20DE => 1, 0x20DF => 1, 0x20E0 => 1, 0x20E1 => 1, 0x20E2 => 1, 0x20E3 => 1, 0x20E4 => 1,
		0x20E5 => 1, 0x20E6 => 1, 0x20E7 => 1, 0x20E8 => 1, 0x20E9 => 1, 0x20EA => 1, 0x20EB => 1, 0x20EC => 1,
		0x20ED => 1, 0x20EE => 1, 0x20EF => 1, 0x20F0 => 1, 0x302A => 1, 0x302B => 1, 0x302C => 1, 0x302D => 1,
		0x3099 => 1, 0x309A => 1, 0xFE00 => 1, 0xFE01 => 1, 0xFE02 => 1, 0xFE03 => 1, 0xFE04 => 1, 0xFE05 => 1,
		0xFE06 => 1, 0xFE07 => 1, 0xFE08 => 1, 0xFE09 => 1, 0xFE0A => 1, 0xFE0B => 1, 0xFE0C => 1, 0xFE0D => 1,
		0xFE0E => 1, 0xFE0F => 1, 0xFE20 => 1, 0xFE21 => 1, 0xFE22 => 1, 0xFE23 => 1, 0xFE24 => 1, 0xFE25 => 1,
		0xFE26 => 1, 0xFE27 => 1, 0xFE28 => 1, 0xFE29 => 1, 0xFE2A => 1, 0xFE2B => 1, 0xFE2C => 1, 0xFE2D => 1,
		0xFEFF => 1, 0xFFF9 => 1, 0xFFFA => 1, 0xFFFB => 1, 0x101FD => 1, 0x102E0 => 1, 0x10ECB => 1, 0x10ECC => 1,
		0x10ECD => 1, 0x10ECE => 1, 0x10ECF => 1, 0x10EF0 => 1, 0x10EF1 => 1, 0x10EF2 => 1, 0x10EF3 => 1, 0x10EF4 => 1,
		0x10EF5 => 1, 0x10EF6 => 1, 0x10EF7 => 1, 0x10EF8 => 1, 0x10EF9 => 1, 0x10EFA => 1, 0x10EFB => 1, 0x10EFC => 1,
		0x10EFD => 1, 0x10EFE => 1, 0x10EFF => 1, 0x1133B => 1, 0x1BCA0 => 1, 0x1BCA1 => 1, 0x1BCA2 => 1, 0x1BCA3 => 1,
		0x1CF00 => 1, 0x1CF01 => 1, 0x1CF02 => 1, 0x1CF03 => 1, 0x1CF04 => 1, 0x1CF05 => 1, 0x1CF06 => 1, 0x1CF07 => 1,
		0x1CF08 => 1, 0x1CF09 => 1, 0x1CF0A => 1, 0x1CF0B => 1, 0x1CF0C => 1, 0x1CF0D => 1, 0x1CF0E => 1, 0x1CF0F => 1,
		0x1CF10 => 1, 0x1CF11 => 1, 0x1CF12 => 1, 0x1CF13 => 1, 0x1CF14 => 1, 0x1CF15 => 1, 0x1CF16 => 1, 0x1CF17 => 1,
		0x1CF18 => 1, 0x1CF19 => 1, 0x1CF1A => 1, 0x1CF1B => 1, 0x1CF1C => 1, 0x1CF1D => 1, 0x1CF1E => 1, 0x1CF1F => 1,
		0x1CF20 => 1, 0x1CF21 => 1, 0x1CF22 => 1, 0x1CF23 => 1, 0x1CF24 => 1, 0x1CF25 => 1, 0x1CF26 => 1, 0x1CF27 => 1,
		0x1CF28 => 1, 0x1CF29 => 1, 0x1CF2A => 1, 0x1CF2B => 1, 0x1CF2C => 1, 0x1CF2D => 1, 0x1CF30 => 1, 0x1CF31 => 1,
		0x1CF32 => 1, 0x1CF33 => 1, 0x1CF34 => 1, 0x1CF35 => 1, 0x1CF36 => 1, 0x1CF37 => 1, 0x1CF38 => 1, 0x1CF39 => 1,
		0x1CF3A => 1, 0x1CF3B => 1, 0x1CF3C => 1, 0x1CF3D => 1, 0x1CF3E => 1, 0x1CF3F => 1, 0x1CF40 => 1, 0x1CF41 => 1,
		0x1CF42 => 1, 0x1CF43 => 1, 0x1CF44 => 1, 0x1CF45 => 1, 0x1CF46 => 1, 0x1D127 => 1, 0x1D128 => 1, 0x1D167 => 1,
		0x1D168 => 1, 0x1D169 => 1, 0x1D173 => 1, 0x1D174 => 1, 0x1D175 => 1, 0x1D176 => 1, 0x1D177 => 1, 0x1D178 => 1,
		0x1D179 => 1, 0x1D17A => 1, 0x1D17B => 1, 0x1D17C => 1, 0x1D17D => 1, 0x1D17E => 1, 0x1D17F => 1, 0x1D180 => 1,
		0x1D181 => 1, 0x1D182 => 1, 0x1D185 => 1, 0x1D186 => 1, 0x1D187 => 1, 0x1D188 => 1, 0x1D189 => 1, 0x1D18A => 1,
		0x1D18B => 1, 0x1D1AA => 1, 0x1D1AB => 1, 0x1D1AC => 1, 0x1D1AD => 1, 0x1D25B => 1, 0x1D25C => 1, 0xE0001 => 1,
		0xE0020 => 1, 0xE0021 => 1, 0xE0022 => 1, 0xE0023 => 1, 0xE0024 => 1, 0xE0025 => 1, 0xE0026 => 1, 0xE0027 => 1,
		0xE0028 => 1, 0xE0029 => 1, 0xE002A => 1, 0xE002B => 1, 0xE002C => 1, 0xE002D => 1, 0xE002E => 1, 0xE002F => 1,
		0xE0030 => 1, 0xE0031 => 1, 0xE0032 => 1, 0xE0033 => 1, 0xE0034 => 1, 0xE0035 => 1, 0xE0036 => 1, 0xE0037 => 1,
		0xE0038 => 1, 0xE0039 => 1, 0xE003A => 1, 0xE003B => 1, 0xE003C => 1, 0xE003D => 1, 0xE003E => 1, 0xE003F => 1,
		0xE0040 => 1, 0xE0041 => 1, 0xE0042 => 1, 0xE0043 => 1, 0xE0044 => 1, 0xE0045 => 1, 0xE0046 => 1, 0xE0047 => 1,
		0xE0048 => 1, 0xE0049 => 1, 0xE004A => 1, 0xE004B => 1, 0xE004C => 1, 0xE004D => 1, 0xE004E => 1, 0xE004F => 1,
		0xE0050 => 1, 0xE0051 => 1, 0xE0052 => 1, 0xE0053 => 1, 0xE0054 => 1, 0xE0055 => 1, 0xE0056 => 1, 0xE0057 => 1,
		0xE0058 => 1, 0xE0059 => 1, 0xE005A => 1, 0xE005B => 1, 0xE005C => 1, 0xE005D => 1, 0xE005E => 1, 0xE005F => 1,
		0xE0060 => 1, 0xE0061 => 1, 0xE0062 => 1, 0xE0063 => 1, 0xE0064 => 1, 0xE0065 => 1, 0xE0066 => 1, 0xE0067 => 1,
		0xE0068 => 1, 0xE0069 => 1, 0xE006A => 1, 0xE006B => 1, 0xE006C => 1, 0xE006D => 1, 0xE006E => 1, 0xE006F => 1,
		0xE0070 => 1, 0xE0071 => 1, 0xE0072 => 1, 0xE0073 => 1, 0xE0074 => 1, 0xE0075 => 1, 0xE0076 => 1, 0xE0077 => 1,
		0xE0078 => 1, 0xE0079 => 1, 0xE007A => 1, 0xE007B => 1, 0xE007C => 1, 0xE007D => 1, 0xE007E => 1, 0xE007F => 1,
		0xE0100 => 1, 0xE0101 => 1, 0xE0102 => 1, 0xE0103 => 1, 0xE0104 => 1, 0xE0105 => 1, 0xE0106 => 1, 0xE0107 => 1,
		0xE0108 => 1, 0xE0109 => 1, 0xE010A => 1, 0xE010B => 1, 0xE010C => 1, 0xE010D => 1, 0xE010E => 1, 0xE010F => 1,
		0xE0110 => 1, 0xE0111 => 1, 0xE0112 => 1, 0xE0113 => 1, 0xE0114 => 1, 0xE0115 => 1, 0xE0116 => 1, 0xE0117 => 1,
		0xE0118 => 1, 0xE0119 => 1, 0xE011A => 1, 0xE011B => 1, 0xE011C => 1, 0xE011D => 1, 0xE011E => 1, 0xE011F => 1,
		0xE0120 => 1, 0xE0121 => 1, 0xE0122 => 1, 0xE0123 => 1, 0xE0124 => 1, 0xE0125 => 1, 0xE0126 => 1, 0xE0127 => 1,
		0xE0128 => 1, 0xE0129 => 1, 0xE012A => 1, 0xE012B => 1, 0xE012C => 1, 0xE012D => 1, 0xE012E => 1, 0xE012F => 1,
		0xE0130 => 1, 0xE0131 => 1, 0xE0132 => 1, 0xE0133 => 1, 0xE0134 => 1, 0xE0135 => 1, 0xE0136 => 1, 0xE0137 => 1,
		0xE0138 => 1, 0xE0139 => 1, 0xE013A => 1, 0xE013B => 1, 0xE013C => 1, 0xE013D => 1, 0xE013E => 1, 0xE013F => 1,
		0xE0140 => 1, 0xE0141 => 1, 0xE0142 => 1, 0xE0143 => 1, 0xE0144 => 1, 0xE0145 => 1, 0xE0146 => 1, 0xE0147 => 1,
		0xE0148 => 1, 0xE0149 => 1, 0xE014A => 1, 0xE014B => 1, 0xE014C => 1, 0xE014D => 1, 0xE014E => 1, 0xE014F => 1,
		0xE0150 => 1, 0xE0151 => 1, 0xE0152 => 1, 0xE0153 => 1, 0xE0154 => 1, 0xE0155 => 1, 0xE0156 => 1, 0xE0157 => 1,
		0xE0158 => 1, 0xE0159 => 1, 0xE015A => 1, 0xE015B => 1, 0xE015C => 1, 0xE015D => 1, 0xE015E => 1, 0xE015F => 1,
		0xE0160 => 1, 0xE0161 => 1, 0xE0162 => 1, 0xE0163 => 1, 0xE0164 => 1, 0xE0165 => 1, 0xE0166 => 1, 0xE0167 => 1,
		0xE0168 => 1, 0xE0169 => 1, 0xE016A => 1, 0xE016B => 1, 0xE016C => 1, 0xE016D => 1, 0xE016E => 1, 0xE016F => 1,
		0xE0170 => 1, 0xE0171 => 1, 0xE0172 => 1, 0xE0173 => 1, 0xE0174 => 1, 0xE0175 => 1, 0xE0176 => 1, 0xE0177 => 1,
		0xE0178 => 1, 0xE0179 => 1, 0xE017A => 1, 0xE017B => 1, 0xE017C => 1, 0xE017D => 1, 0xE017E => 1, 0xE017F => 1,
		0xE0180 => 1, 0xE0181 => 1, 0xE0182 => 1, 0xE0183 => 1, 0xE0184 => 1, 0xE0185 => 1, 0xE0186 => 1, 0xE0187 => 1,
		0xE0188 => 1, 0xE0189 => 1, 0xE018A => 1, 0xE018B => 1, 0xE018C => 1, 0xE018D => 1, 0xE018E => 1, 0xE018F => 1,
		0xE0190 => 1, 0xE0191 => 1, 0xE0192 => 1, 0xE0193 => 1, 0xE0194 => 1, 0xE0195 => 1, 0xE0196 => 1, 0xE0197 => 1,
		0xE0198 => 1, 0xE0199 => 1, 0xE019A => 1, 0xE019B => 1, 0xE019C => 1, 0xE019D => 1, 0xE019E => 1, 0xE019F => 1,
		0xE01A0 => 1, 0xE01A1 => 1, 0xE01A2 => 1, 0xE01A3 => 1, 0xE01A4 => 1, 0xE01A5 => 1, 0xE01A6 => 1, 0xE01A7 => 1,
		0xE01A8 => 1, 0xE01A9 => 1, 0xE01AA => 1, 0xE01AB => 1, 0xE01AC => 1, 0xE01AD => 1, 0xE01AE => 1, 0xE01AF => 1,
		0xE01B0 => 1, 0xE01B1 => 1, 0xE01B2 => 1, 0xE01B3 => 1, 0xE01B4 => 1, 0xE01B5 => 1, 0xE01B6 => 1, 0xE01B7 => 1,
		0xE01B8 => 1, 0xE01B9 => 1, 0xE01BA => 1, 0xE01BB => 1, 0xE01BC => 1, 0xE01BD => 1, 0xE01BE => 1, 0xE01BF => 1,
		0xE01C0 => 1, 0xE01C1 => 1, 0xE01C2 => 1, 0xE01C3 => 1, 0xE01C4 => 1, 0xE01C5 => 1, 0xE01C6 => 1, 0xE01C7 => 1,
		0xE01C8 => 1, 0xE01C9 => 1, 0xE01CA => 1, 0xE01CB => 1, 0xE01CC => 1, 0xE01CD => 1, 0xE01CE => 1, 0xE01CF => 1,
		0xE01D0 => 1, 0xE01D1 => 1, 0xE01D2 => 1, 0xE01D3 => 1, 0xE01D4 => 1, 0xE01D5 => 1, 0xE01D6 => 1, 0xE01D7 => 1,
		0xE01D8 => 1, 0xE01D9 => 1, 0xE01DA => 1, 0xE01DB => 1, 0xE01DC => 1, 0xE01DD => 1, 0xE01DE => 1, 0xE01DF => 1,
		0xE01E0 => 1, 0xE01E1 => 1, 0xE01E2 => 1, 0xE01E3 => 1, 0xE01E4 => 1, 0xE01E5 => 1, 0xE01E6 => 1, 0xE01E7 => 1,
		0xE01E8 => 1, 0xE01E9 => 1, 0xE01EA => 1, 0xE01EB => 1, 0xE01EC => 1, 0xE01ED => 1, 0xE01EE => 1, 0xE01EF => 1,
	];

	/**
	 * Arabic ligatures in presentation form, which a font's 'ccmp' produces - Arial and Times among them.
	 * Unicode gives them no joining type at all, so no database states them and the generator cannot
	 * write them; they are kept by hand here and read alongside the table above.
	 *
	 * Others in the U+FC00 range still need adding. Whether any of them belongs here is #267: Unicode
	 * leaves the whole range Non_Joining, which is a base rather than something joining reads over.
	 */
	private static $presentationLigatures = [0xFC5E => 1, 0xFC5F => 1, 0xFC60 => 1, 0xFC61 => 1, 0xFC62 => 1];

	/**
	 * The joining group DALATH RISH of ArabicShaping.txt, which with ALAPH is the whole of what the
	 * joining state table reads beyond the joining types. All four letters are right-joining, so an
	 * Alaph after one of them stands apart from it, and fin3 is the form Syriac states for that.
	 */
	private static $dalathRish = [0x0715 => 1, 0x0716 => 1, 0x072A => 1, 0x072F => 1];

	/** The feature each resolved action is stated under, in the order rtlSUB indexes a letter's forms in */
	private static $actionFeatures = ['isol', 'fina', 'init', 'medi', 'med2', 'fin2', 'fin3'];

	/**
	 * The same order read the other way, which is the half of it the parser needs: TTFontFile files a
	 * rule read under isol in slot 0, one read under fina in slot 1, and so on, and glyphs() reads the
	 * slot back by the action it resolved. Stated here because this is the class the order is for.
	 *
	 * @return int[] The rtlSUB slot of each joining form, by the feature tag that states it
	 */
	public static function formSlots()
	{
		return array_flip(self::$actionFeatures);
	}

	/**
	 * Read the form each character of the run calls for out of the joining classes, and write it into
	 * the run as `joining`.
	 *
	 * Read from the characters as written, and so before anything is substituted into the run, because
	 * a substitution can leave a glyph that is no character at all. Where 'ccmp' takes a dotted letter
	 * apart into its rasm and its dots - Noto Sans Arabic does this for beh - the rasm is unencoded,
	 * mPDF has mapped it into the Private Use Area, and a Private Use codepoint is in none of the
	 * joining tables, so the letter would join nothing and neither would its neighbours through it.
	 * HarfBuzz resolves joining in setup_masks() before it applies GSUB for the same reason, and a
	 * glyph a substitution produces carries the mask of the character it came from.
	 *
	 * @param array[] $info            The run, by reference: each character's joining is written into it
	 * @param string  $glyphClassMarks The mark glyphs of GDEF, which join as a vowel does
	 * @param string  $scriptTag       'arab', 'syrc', 'nko ' or 'mand'
	 */
	public static function resolveJoining(&$info, $glyphClassMarks, $scriptTag)
	{
		$transparentJoin = self::transparentJoining($glyphClassMarks);
		$chars = self::hexes($info);

		$nextChar = null;
		for ($i = count($chars) - 1; $i >= 0; $i--) {
			$crntChar = $chars[$i];
			// joining sees the base a mark is written on, however many marks the base carries: behind
			// the position that means walking over them, and in front it means $nextChar, which a
			// transparent-joining character continues without writing
			$n = self::skipTransparent($chars, $i, $transparentJoin);
			$prevChar = isset($chars[$n]) ? hexdec($chars[$n]) : null;
			$joinedToPrevious = $prevChar && isset(self::$leftJoining[$prevChar]);
			$joinedToNext = $nextChar && isset(self::$rightJoining[hexdec($nextChar)]);
			if ($crntChar && isset($transparentJoin[hexdec($crntChar)])) {
				// a transparent-joining character takes a <final> form where letters that join stand
				// either side of it and an <isolated> one otherwise; it never takes a medial or initial
				$info[$i]['joining'] = $joinedToPrevious && $joinedToNext ? 1 : 0;
				continue;
			}
			if (hexdec($crntChar) < 128) {
				$info[$i]['joining'] = 0;
				$nextChar = $crntChar;
				continue;
			}
			if ($scriptTag == 'syrc' && $crntChar == '00710') {
				$action = self::alaphAction($prevChar, $joinedToPrevious, $joinedToNext);
			} else {
				// The four joining-type columns of the state table alaphAction() reads collapse the same
				// way: a letter's own action is <final> where the letter before it joins forwards and
				// <isolated> otherwise, and the table's INIT and MEDI - written back over it once the
				// letter after it turns out to join backwards - are what the +2 adds here
				$action = 0;
				if ($joinedToPrevious) {
					$action++;
				}
				if ($joinedToNext) {
					$action += 2;
				}
			}
			$info[$i]['joining'] = $action;
			$nextChar = $crntChar;
		}
	}

	/**
	 * The action the Syriac Alaph U+0710 calls for, read off the ALAPH column of the joining table.
	 *
	 * Syriac states three forms for the Alaph that no other letter has, and HarfBuzz resolves them in
	 * arabic_joining() from the same state table as the other four, letting each state rewrite the
	 * action it has already decided for the character behind it. resolveJoining() decides each
	 * character from its neighbours instead, and for the Alaph the two agree, because every state an
	 * Alaph can be reached in from a given kind of letter holds the same action for it, and the only
	 * rewrites that land on an Alaph - state 4's med2 over a fina and state 5's isol over a fin2 or a
	 * fin3 - both come of a letter that joins backwards following it.
	 *
	 * There is no test here for whether the Alaph ends the word, nor for whether what stands either
	 * side of it is Syriac. HarfBuzz has neither, and reading the joining classes alone is what puts
	 * the Sogdian letters U+074D to U+074F on the same footing as the rest of the block.
	 *
	 * @param int|null $prevChar         The base before the Alaph, past any transparent-joining characters
	 * @param bool     $joinedToPrevious Whether that base is one that joins to what follows it
	 * @param bool     $joinedToNext     Whether the base after the Alaph joins to what precedes it
	 *
	 * @return int 0=ISOL, 1=FINA, 4=MED2, 5=FIN2, 6=FIN3
	 */
	private static function alaphAction($prevChar, $joinedToPrevious, $joinedToNext)
	{
		if ($joinedToPrevious) {
			return $joinedToNext ? 4 : 1;
		}

		// nothing stands before the Alaph for it to be drawn apart from, or a letter follows it that
		// joins back over the form the Alaph would otherwise have taken
		if ($prevChar === null || !isset(self::$rightJoining[$prevChar]) || $joinedToNext) {
			return 0;
		}

		return isset(self::$dalathRish[$prevChar]) ? 6 : 5;
	}

	/**
	 * Put every character of the run into the form resolveJoining() said its joining calls for.
	 *
	 * A form is usually one glyph and is written straight into $info. It need not be: a font may state
	 * one as a base glyph and the marks drawn on it, which is how the Nastaliq faces write their
	 * initial and medial forms. One character is then several glyphs, and making a run longer is the
	 * caller's to do - it holds the ligature and mark bookkeeping that a change in length disturbs -
	 * so such a form is handed back whole for the caller to substitute.
	 *
	 * @param array[] $info       The run, by reference: the form substituted is written into it
	 * @param array   $arabGlyphs The font's rtlSUB table: the glyph for each form of each letter
	 * @param string  $usetags    Which of the form features the document left switched on
	 *
	 * @return int[][] The forms of more than one glyph, as the code points to put in the character's
	 *                 place, keyed by the position in $info it has
	 */
	public static function shape(&$info, $arabGlyphs, $usetags)
	{
		$chars = self::hexes($info);

		$multiple = [];
		for ($i = 0; $i < count($chars); $i++) {
			list($substitute, $form) = self::glyphs($chars[$i], $info[$i]['joining'], $chars, $i, $usetags, $arabGlyphs);

			// rtlSUB writes a form of several glyphs as one space-separated string, which hexdec()
			// would read as a single code point
			$glyphs = explode(' ', $substitute);

			$info[$i]['uni'] = hexdec($glyphs[0]);
			$info[$i]['hex'] = $glyphs[0];
			$info[$i]['form'] = $form; // Actaul form substituted 0=ISOLATED FORM :: 1=FINAL :: 2=INITIAL :: 3=MEDIAL

			if (count($glyphs) > 1) {
				$multiple[$i] = array_map('hexdec', $glyphs);
			}
		}

		return $multiple;
	}

	/**
	 * The run as hex code points, which is what joining and the context rules are matched against.
	 *
	 * Read once either side of the substitutions that stand between resolveJoining() and shape(), so
	 * the two need not be the same run: 'ccmp' may have made it longer.
	 */
	private static function hexes($info)
	{
		$chars = [];
		for ($i = 0; $i < count($info); $i++) {
			$chars[] = $info[$i]['hex'];
		}

		return $chars;
	}

	/**
	 * The Transparent-Joining table for this string.
	 *
	 * A GDEF mark is transparent to joining just as a vowel is, so the mark class joins the table, as do
	 * the presentation-form ligatures Unicode states no joining type for. Array + keeps the left operand
	 * on collision, so a codepoint in more than one stays as the Unicode table has it.
	 */
	private static function transparentJoining($glyphClassMarks)
	{
		$gcm = [];
		foreach (explode('| ', $glyphClassMarks) as $g) {
			$gcm[hexdec($g)] = 1;
		}

		return self::$transparent + self::$presentationLigatures + $gcm;
	}

	/**
	 * The position behind $i that joining sees, which is the first one past any transparent-joining
	 * characters.
	 *
	 * @param array $chars           The run, as hex code points
	 * @param int   $i               The position to walk back from
	 * @param array $transparentJoin The Transparent-Joining table, with GDEF's marks
	 *
	 * @return int The position reached, which the run need not hold
	 */
	private static function skipTransparent(&$chars, $i, $transparentJoin)
	{
		$n = $i - 1;
		while (isset($chars[$n]) && isset($transparentJoin[hexdec($chars[$n])])) {
			$n--;
		}

		return $n;
	}

	private static function glyphs($char, $action, &$chars, $i, $usetags, $arabGlyphs)
	{
		// A form whose feature the document switched off through OTLtags is not substituted, Syriac's
		// three extra forms included
		if (strpos($usetags, self::$actionFeatures[$action]) === false) {
			return [$char, 0];
		}

		if (isset($arabGlyphs[$char][$action])) {
			$retk = $action;
		} elseif ($action == 3 && isset($arabGlyphs[$char][1])) { // if <medial> not defined, but <final>, return <final>
			$retk = 1;
		} elseif ($action == 2 && isset($arabGlyphs[$char][0])) { // if <initial> not defined, but <isolated>, return <isolated>
			$retk = 0;
		} else {
			return [$char, 0];
		}

		$match = true;
		// If GSUB includes a Backtrack or Lookahead condition (e.g. font ArabicTypesetting)
		// The walk over ignored glyphs stops at the edge of the run, and a position it runs out before
		// reaching is not held, as in HarfBuzz's match_backtrack() and match_lookahead(). Past the edge
		// the glyph is null, which inList() finds in any pattern from PHP 8, so the walk would not end.
		if (isset($arabGlyphs[$char]['prel'][$retk]) && $arabGlyphs[$char]['prel'][$retk]) {
			$ig = 1;
			foreach ($arabGlyphs[$char]['prel'][$retk] as $k => $v) { // $k starts 0, 1...
				if (!isset($chars[$i - $ig - $k])) {
					$match = false;
				} elseif (!GlyphString::inList($v, $chars[$i - $ig - $k])) {
					while (isset($chars[$i - $ig - $k]) && GlyphString::inList($arabGlyphs[$char]['ignore'][$retk], $chars[$i - $ig - $k])) {
						$ig++;
					}
					if (!isset($chars[$i - $ig - $k])) {
						$match = false;
					} elseif (!GlyphString::inList($v, $chars[$i - $ig - $k])) {
						$match = false;
					}
				}
			}
		}
		if (isset($arabGlyphs[$char]['postl'][$retk]) && $arabGlyphs[$char]['postl'][$retk]) {
			$ig = 1;
			foreach ($arabGlyphs[$char]['postl'][$retk] as $k => $v) { // $k starts 0, 1...
				if (!isset($chars[$i + $ig + $k])) {
					$match = false;
				} elseif (!GlyphString::inList($v, $chars[$i + $ig + $k])) {
					while (isset($chars[$i + $ig + $k]) && GlyphString::inList($arabGlyphs[$char]['ignore'][$retk], $chars[$i + $ig + $k])) {
						$ig++;
					}
					if (!isset($chars[$i + $ig + $k])) {
						$match = false;
					} elseif (!GlyphString::inList($v, $chars[$i + $ig + $k])) {
						$match = false;
					}
				}
			}
		}

		return $match ? [$arabGlyphs[$char][$retk], $retk] : [$char, 0];
	}
}
