<?php

namespace Mpdf\Fonts;

use Mpdf\Cache;
use Mpdf\TTFontFile;

/**
 * Captures the font programs the subsetter emits, byte for byte, for one font.
 *
 * The other two masters pin what the parser reads. This pins what the writer writes, which nothing
 * else looks at: makeSubset, makeSubsetSIP and repackageTTF each build a whole font file out of
 * hand-packed big-endian records, and their only consumer is Writer\FontWriter, which passes the
 * bytes straight into the PDF. A change in them is invisible to every other test in the suite and
 * shows up as a font that will not load in a reader.
 *
 * #81 established that these programs are byte-identical across the corpus while the reader moved
 * under them, but checked it by hand. This is that check, committed.
 *
 * The three values the writer hands back besides the bytes - codeToGlyph, maxUni and defaultWidth
 * - are captured with them, because FontWriter reads all three off the subsetter after the call and
 * one that emitted the right bytes but stopped setting them would produce a PDF with the wrong
 * widths in it.
 */
class SubsetGoldenMaster extends GoldenMaster
{

	/**
	 * The subsetter is called once per useOTL setting a document can ask for. 0 is a font used as
	 * plain text; 0xFF is every OTL feature on, which is what mPDF passes for a complex script, and
	 * it takes a different path through both the glyph mapping and the tables that get copied.
	 */
	private static $useOtlSettings = [0, 0xFF];

	/**
	 * The three font programs the subsetter can emit, and what each leaves on the subsetter besides
	 * the bytes. FontWriter reads these off it after the call - defaultWidth for a character
	 * the subset has no width for, codeToGlyph for the CIDToGIDMap, maxUni to bound the widths array - so
	 * they are as much the output as the program is, and a method that stopped setting one would
	 * write a PDF with the wrong widths and pass every other test.
	 *
	 * makeSubsetSIP is captured over the same characters as the other two even though no font in the
	 * corpus reaches beyond the Basic Multilingual Plane. It wants a format 12 cmap and finds none, so
	 * what it emits is a font with an empty glyf table - which is not useful output, but is output,
	 * and pinning it is what stops the 510 lines that produce it from drifting unwatched.
	 */
	private static $entryPoints = [
		'makeSubset' => ['maxUni', 'defaultWidth', 'codeToGlyph'],
		'makeSubsetSIP' => ['maxUniChar', 'defaultWidth'],
		'repackageTTF' => ['maxUni'],
	];

	/**
	 * @return string The fixture as it would be written now
	 */
	protected function name()
	{
		return 'subset';
	}

	/**
	 * @return string The extension its fixtures are written with
	 */
	protected function extension()
	{
		return 'json';
	}

	/**
	 * @param string $name A font name, as fonts() gives it
	 *
	 * @return string The font programs the three subsetting entry points emit, table by table
	 */
	public function capture($name)
	{
		$file = self::FONT_DIR . '/' . $name . '.ttf';

		$capture = ['_' => 'Generated by composer subset:update. See tests/Mpdf/Fonts/SubsetGoldenMaster.php.'];

		foreach (self::$useOtlSettings as $useOtl) {
			// The characters the document would have asked for: everything this font can map, which
			// under useOTL includes the Private Use Area codes the parser assigns to glyphs the cmap
			// reaches only through a substitution. Taken from the parser rather than written down, so
			// that a font added to the corpus needs no entry here.
			$subset = array_keys($this->parser()->getCTG($file, 0, false, $useOtl));
			sort($subset);

			$built = ['characters' => count($subset)];
			foreach (self::$entryPoints as $method => $handedBack) {
				$built[$method] = $this->build($file, $method, $subset, $useOtl, $handedBack);
			}

			$capture[sprintf('useOTL=0x%02X', $useOtl)] = $built;
		}

		return json_encode($capture, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n";
	}

	/**
	 * One font program, plus whatever the call left on the parser for FontWriter to read.
	 */
	private function build($file, $method, $subset, $useOtl, array $handedBack)
	{
		$subsetter = new FontSubsetter($this->parser());

		try {
			// repackageTTF rewrites the whole font rather than a subset, so it takes no character list
			$program = $method === 'repackageTTF'
				? $subsetter->repackageTTF($file, 0, false, $useOtl)
				: $subsetter->$method($file, $subset, 0, false, $useOtl);
		} catch (\Exception $e) {
			return sprintf('%s: %s', get_class($e), $this->withoutPath($e->getMessage()));
		}

		$built = [
			'bytes' => strlen($program),
			'sha256' => hash('sha256', $program),
			'tables' => $this->tableDirectory($program),
		];

		foreach ($handedBack as $property) {
			$value = $subsetter->$property;

			// codeToGlyph runs to thousands of entries on a text font, and a hash catches a moved one
			// as well as a listing would
			$built[$property] = is_array($value)
				? sprintf('%d entries, sha256 %s', count($value), hash('sha256', json_encode($value)))
				: $value;
		}

		return $built;
	}

	/**
	 * The emitted font's own table directory.
	 *
	 * The whole-program hash is the assertion; this is so that a diff says which table moved instead
	 * of only that something did. Tables are listed in the order the directory gives them, which is
	 * alphabetical by tag - endTTFile sorts them - so a table appearing or disappearing reads as one
	 * line rather than shifting everything below it.
	 */
	private function tableDirectory($program)
	{
		$reader = new BlobReader($program);
		$reader->skip(4); // sfntVersion
		$numTables = $reader->readUInt16();
		$reader->skip(6); // searchRange, entrySelector, rangeShift

		$tables = [];
		for ($i = 0; $i < $numTables; $i++) {
			$tag = $reader->read(4);
			$checksum = FontReader::uint32($reader->read(4));
			$offset = FontReader::uint32($reader->read(4));
			$length = FontReader::uint32($reader->read(4));

			$tables[$tag] = sprintf(
				'%d bytes, checksum 0x%08X, sha256 %s',
				$length,
				$checksum,
				hash('sha256', substr($program, $offset, $length))
			);
		}

		return $tables;
	}

	/**
	 * @return TTFontFile A parser reading into this master's scratch directory
	 */
	private function parser()
	{
		return new TTFontFile(new FontCache(new Cache($this->tmpDir)), 'win');
	}
}
