<?php

namespace Mpdf\Unicode;

/**
 * Where an emoji starts and ends in a run of text, and whether it asks to be drawn in colour.
 *
 * A single emoji can be many codepoints: a family is three people joined by ZERO WIDTH JOINER, a
 * flag is two regional indicators, a keycap is a digit and U+20E3, a skin tone follows the person
 * it colours, and the flags of England, Scotland and Wales are a black flag followed by tag
 * characters. The font draws each as one glyph, which its GSUB forms from the whole sequence, so the
 * sequence has to reach one font in one piece. clusters() finds those sequences, following the
 * grammar of UTS #51.
 *
 * The property tables are generated by composer emoji:update from emoji-data.txt - see
 * tests/Mpdf/Unicode/EmojiTables.php.
 *
 * @see https://www.unicode.org/reports/tr51/#Definitions
 */
class Emoji
{

	const ZWJ = 0x200D;

	const TEXT_SELECTOR = 0xFE0E;

	const EMOJI_SELECTOR = 0xFE0F;

	const KEYCAP = 0x20E3;

	const CANCEL_TAG = 0xE007F;

	/**
	 * Asks for colour: Emoji_Presentation, U+FE0F, or any sequence longer than one emoji
	 */
	const PRESENTATION_EMOJI = 'emoji';

	/**
	 * Asks for a text font, with U+FE0E
	 */
	const PRESENTATION_TEXT = 'text';

	/**
	 * Asks for nothing: an emoji that is text by default, with no selector after it
	 */
	const PRESENTATION_DEFAULT = '';

	// UNIDATA_VERSION 18.0.0
	/**
	 * Emoji_Presentation=Yes: drawn as emoji even with no U+FE0F after them
	 */
	private static $emojiPresentation = [
		[0x231A, 0x231B], [0x23E9, 0x23EC], [0x23F0, 0x23F0], [0x23F3, 0x23F3],
		[0x25FD, 0x25FE], [0x2614, 0x2615], [0x2648, 0x2653], [0x267F, 0x267F],
		[0x2693, 0x2693], [0x26A1, 0x26A1], [0x26AA, 0x26AB], [0x26BD, 0x26BE],
		[0x26C4, 0x26C5], [0x26CE, 0x26CE], [0x26D4, 0x26D4], [0x26EA, 0x26EA],
		[0x26F2, 0x26F3], [0x26F5, 0x26F5], [0x26FA, 0x26FA], [0x26FD, 0x26FD],
		[0x2705, 0x2705], [0x270A, 0x270B], [0x2728, 0x2728], [0x274C, 0x274C],
		[0x274E, 0x274E], [0x2753, 0x2755], [0x2757, 0x2757], [0x2795, 0x2797],
		[0x27B0, 0x27B0], [0x27BF, 0x27BF], [0x2B1B, 0x2B1C], [0x2B50, 0x2B50],
		[0x2B55, 0x2B55], [0x1F004, 0x1F004], [0x1F0CF, 0x1F0CF], [0x1F18E, 0x1F18E],
		[0x1F191, 0x1F19A], [0x1F1E6, 0x1F1FF], [0x1F201, 0x1F201], [0x1F21A, 0x1F21A],
		[0x1F22F, 0x1F22F], [0x1F232, 0x1F236], [0x1F238, 0x1F23A], [0x1F250, 0x1F251],
		[0x1F300, 0x1F320], [0x1F32D, 0x1F335], [0x1F337, 0x1F37C], [0x1F37E, 0x1F393],
		[0x1F3A0, 0x1F3CA], [0x1F3CF, 0x1F3D3], [0x1F3E0, 0x1F3F0], [0x1F3F4, 0x1F3F4],
		[0x1F3F8, 0x1F43E], [0x1F440, 0x1F440], [0x1F442, 0x1F4FC], [0x1F4FF, 0x1F53D],
		[0x1F54B, 0x1F54E], [0x1F550, 0x1F567], [0x1F57A, 0x1F57A], [0x1F595, 0x1F596],
		[0x1F5A4, 0x1F5A4], [0x1F5FB, 0x1F64F], [0x1F680, 0x1F6C5], [0x1F6CC, 0x1F6CC],
		[0x1F6D0, 0x1F6D2], [0x1F6D5, 0x1F6D9], [0x1F6DC, 0x1F6DF], [0x1F6EB, 0x1F6EC],
		[0x1F6F4, 0x1F6FC], [0x1F7E0, 0x1F7EB], [0x1F7F0, 0x1F7F0], [0x1F90C, 0x1F93A],
		[0x1F93C, 0x1F945], [0x1F947, 0x1F9FF], [0x1FA70, 0x1FA7C], [0x1FA80, 0x1FAC6],
		[0x1FAC8, 0x1FAC8], [0x1FACC, 0x1FADD], [0x1FADF, 0x1FAEB], [0x1FAEF, 0x1FAFA],
	];

	/**
	 * Emoji_Modifier_Base=Yes: the emoji a skin tone can follow
	 */
	private static $emojiModifierBase = [
		[0x261D, 0x261D], [0x26F9, 0x26F9], [0x270A, 0x270D], [0x1F385, 0x1F385],
		[0x1F3C2, 0x1F3C4], [0x1F3C7, 0x1F3C7], [0x1F3CA, 0x1F3CC], [0x1F442, 0x1F443],
		[0x1F446, 0x1F450], [0x1F466, 0x1F478], [0x1F47C, 0x1F47C], [0x1F481, 0x1F483],
		[0x1F485, 0x1F487], [0x1F48F, 0x1F48F], [0x1F491, 0x1F491], [0x1F4AA, 0x1F4AA],
		[0x1F574, 0x1F575], [0x1F57A, 0x1F57A], [0x1F590, 0x1F590], [0x1F595, 0x1F596],
		[0x1F645, 0x1F647], [0x1F64B, 0x1F64F], [0x1F6A3, 0x1F6A3], [0x1F6B4, 0x1F6B6],
		[0x1F6C0, 0x1F6C0], [0x1F6CC, 0x1F6CC], [0x1F90C, 0x1F90C], [0x1F90F, 0x1F90F],
		[0x1F918, 0x1F91F], [0x1F926, 0x1F926], [0x1F930, 0x1F939], [0x1F93C, 0x1F93E],
		[0x1F977, 0x1F977], [0x1F9B5, 0x1F9B6], [0x1F9B8, 0x1F9B9], [0x1F9BB, 0x1F9BB],
		[0x1F9CD, 0x1F9CF], [0x1F9D1, 0x1F9DD], [0x1FAC3, 0x1FAC5], [0x1FAF0, 0x1FAFA],
	];

	/**
	 * Extended_Pictographic=Yes, which reserves the blocks future emoji will be added to, so a ZWJ
	 * sequence naming one newer than these tables is still kept whole
	 */
	private static $extendedPictographic = [
		[0x00A9, 0x00A9], [0x00AE, 0x00AE], [0x203C, 0x203C], [0x2049, 0x2049],
		[0x2122, 0x2122], [0x2139, 0x2139], [0x2194, 0x2199], [0x21A9, 0x21AA],
		[0x231A, 0x231B], [0x2328, 0x2328], [0x23CF, 0x23CF], [0x23E9, 0x23F3],
		[0x23F8, 0x23FA], [0x24C2, 0x24C2], [0x25AA, 0x25AB], [0x25B6, 0x25B6],
		[0x25C0, 0x25C0], [0x25FB, 0x25FE], [0x2600, 0x2604], [0x260E, 0x260E],
		[0x2611, 0x2611], [0x2614, 0x2615], [0x2618, 0x2618], [0x261D, 0x261D],
		[0x2620, 0x2620], [0x2622, 0x2623], [0x2626, 0x2626], [0x262A, 0x262A],
		[0x262E, 0x262F], [0x2638, 0x263A], [0x2640, 0x2640], [0x2642, 0x2642],
		[0x2648, 0x2653], [0x265F, 0x2660], [0x2663, 0x2663], [0x2665, 0x2666],
		[0x2668, 0x2668], [0x267B, 0x267B], [0x267E, 0x267F], [0x2692, 0x2697],
		[0x2699, 0x2699], [0x269B, 0x269C], [0x26A0, 0x26A1], [0x26A7, 0x26A7],
		[0x26AA, 0x26AB], [0x26B0, 0x26B1], [0x26BD, 0x26BE], [0x26C4, 0x26C5],
		[0x26C8, 0x26C8], [0x26CE, 0x26CF], [0x26D1, 0x26D1], [0x26D3, 0x26D4],
		[0x26E9, 0x26EA], [0x26F0, 0x26F5], [0x26F7, 0x26FA], [0x26FD, 0x26FD],
		[0x2702, 0x2702], [0x2705, 0x2705], [0x2708, 0x270D], [0x270F, 0x270F],
		[0x2712, 0x2712], [0x2714, 0x2714], [0x2716, 0x2716], [0x271D, 0x271D],
		[0x2721, 0x2721], [0x2728, 0x2728], [0x2733, 0x2734], [0x2744, 0x2744],
		[0x2747, 0x2747], [0x274C, 0x274C], [0x274E, 0x274E], [0x2753, 0x2755],
		[0x2757, 0x2757], [0x2763, 0x2764], [0x2795, 0x2797], [0x27A1, 0x27A1],
		[0x27B0, 0x27B0], [0x27BF, 0x27BF], [0x2934, 0x2935], [0x2B05, 0x2B07],
		[0x2B1B, 0x2B1C], [0x2B50, 0x2B50], [0x2B55, 0x2B55], [0x3030, 0x3030],
		[0x303D, 0x303D], [0x3297, 0x3297], [0x3299, 0x3299], [0x1F004, 0x1F004],
		[0x1F02C, 0x1F02F], [0x1F094, 0x1F09F], [0x1F0AF, 0x1F0B0], [0x1F0C0, 0x1F0C0],
		[0x1F0CF, 0x1F0D0], [0x1F0F6, 0x1F0FF], [0x1F170, 0x1F171], [0x1F17E, 0x1F17F],
		[0x1F18E, 0x1F18E], [0x1F191, 0x1F19A], [0x1F1AF, 0x1F1E5], [0x1F201, 0x1F20F],
		[0x1F21A, 0x1F21A], [0x1F22F, 0x1F22F], [0x1F232, 0x1F23A], [0x1F23C, 0x1F23F],
		[0x1F249, 0x1F25F], [0x1F266, 0x1F321], [0x1F324, 0x1F393], [0x1F396, 0x1F397],
		[0x1F399, 0x1F39B], [0x1F39E, 0x1F3F0], [0x1F3F3, 0x1F3F5], [0x1F3F7, 0x1F3FA],
		[0x1F400, 0x1F4FD], [0x1F4FF, 0x1F53D], [0x1F549, 0x1F54E], [0x1F550, 0x1F567],
		[0x1F56F, 0x1F570], [0x1F573, 0x1F57A], [0x1F587, 0x1F587], [0x1F58A, 0x1F58D],
		[0x1F590, 0x1F590], [0x1F595, 0x1F596], [0x1F5A4, 0x1F5A5], [0x1F5A8, 0x1F5A8],
		[0x1F5B1, 0x1F5B2], [0x1F5BC, 0x1F5BC], [0x1F5C2, 0x1F5C4], [0x1F5D1, 0x1F5D3],
		[0x1F5DC, 0x1F5DE], [0x1F5E1, 0x1F5E1], [0x1F5E3, 0x1F5E3], [0x1F5E8, 0x1F5E8],
		[0x1F5EF, 0x1F5EF], [0x1F5F3, 0x1F5F3], [0x1F5FA, 0x1F64F], [0x1F680, 0x1F6C5],
		[0x1F6CB, 0x1F6D2], [0x1F6D5, 0x1F6E5], [0x1F6E9, 0x1F6E9], [0x1F6EB, 0x1F6F0],
		[0x1F6F3, 0x1F6FF], [0x1F7DC, 0x1F7F0], [0x1F80C, 0x1F80F], [0x1F848, 0x1F84F],
		[0x1F85A, 0x1F85F], [0x1F888, 0x1F88F], [0x1F8AE, 0x1F8AF], [0x1F8BC, 0x1F8BF],
		[0x1F8C2, 0x1F8CF], [0x1F8D9, 0x1F8FF], [0x1F90C, 0x1F93A], [0x1F93C, 0x1F945],
		[0x1F947, 0x1F9FF], [0x1FA58, 0x1FA5F], [0x1FA6E, 0x1FAFF], [0x1FC00, 0x1FFFD],
	];

	/**
	 * Finds each emoji in a run of text, and whether it asks to be drawn in colour or as text
	 *
	 * A digit counts only as the start of a keycap. A symbol that is text by default, such as ©,
	 * counts even without a selector, with PRESENTATION_DEFAULT.
	 *
	 * @param int[] $codepoints The run of text
	 *
	 * @return array[] Keyed by the index each emoji starts at: [length in codepoints, PRESENTATION_* constant]
	 */
	public static function clusters(array $codepoints)
	{
		$count = count($codepoints);
		$clusters = [];

		for ($i = 0; $i < $count; $i++) {
			$cluster = self::clusterAt($codepoints, $i, $count);
			if ($cluster !== null) {
				$clusters[$i] = $cluster;
				$i += $cluster[0] - 1;
			}
		}

		return $clusters;
	}

	/**
	 * @param int $codepoint
	 *
	 * @return bool Whether this codepoint is only there to shape the emoji around it - a joiner, a
	 *              presentation selector or a tag - and so is no reason to prefer a font that has it
	 */
	public static function isFormatting($codepoint)
	{
		return $codepoint === self::ZWJ
			|| $codepoint === self::TEXT_SELECTOR
			|| $codepoint === self::EMOJI_SELECTOR
			|| self::isTag($codepoint);
	}

	/**
	 * Emoji_Presentation: drawn as an emoji even without a selector asking for it
	 *
	 * @param int $codepoint
	 *
	 * @return bool
	 */
	public static function hasEmojiPresentation($codepoint)
	{
		return self::inRanges(self::$emojiPresentation, $codepoint);
	}

	/**
	 * Emoji_Modifier_Base: an emoji a skin tone after it colours, rather than standing alone
	 *
	 * @param int $codepoint
	 *
	 * @return bool
	 */
	public static function isModifierBase($codepoint)
	{
		return self::inRanges(self::$emojiModifierBase, $codepoint);
	}

	/**
	 * Extended_Pictographic: an emoji, or a codepoint set aside for one, which may be joined to
	 * another by a ZWJ
	 *
	 * @param int $codepoint
	 *
	 * @return bool
	 */
	public static function isExtendedPictographic($codepoint)
	{
		return self::inRanges(self::$extendedPictographic, $codepoint);
	}

	/**
	 * The five skin tones, which are the whole of Emoji_Modifier
	 *
	 * @param int $codepoint
	 *
	 * @return bool
	 */
	public static function isModifier($codepoint)
	{
		return $codepoint >= 0x1F3FB && $codepoint <= 0x1F3FF;
	}

	/**
	 * The 26 letters two of which make a flag
	 *
	 * @param int $codepoint
	 *
	 * @return bool
	 */
	public static function isRegionalIndicator($codepoint)
	{
		return $codepoint >= 0x1F1E6 && $codepoint <= 0x1F1FF;
	}

	/**
	 * TAG SPACE to TAG TILDE, which spell out a subdivision, and CANCEL TAG, which ends it
	 *
	 * @param int $codepoint
	 *
	 * @return bool
	 */
	public static function isTag($codepoint)
	{
		return $codepoint >= 0xE0020 && $codepoint <= self::CANCEL_TAG;
	}

	/**
	 * @param int[] $codepoints The run
	 * @param int   $i          Where in it to look
	 * @param int   $count      How long it is
	 *
	 * @return array|null [length, presentation] of the emoji starting at $i, or null where none does
	 */
	private static function clusterAt(array $codepoints, $i, $count)
	{
		$first = $codepoints[$i];

		if (self::isRegionalIndicator($first)) {
			$length = ($i + 1 < $count && self::isRegionalIndicator($codepoints[$i + 1])) ? 2 : 1;

			return [$length, self::PRESENTATION_EMOJI];
		}

		// A keycap: 0-9, # or *, an optional U+FE0F, then U+20E3
		if (($first >= 0x30 && $first <= 0x39) || $first === 0x23 || $first === 0x2A) {
			$next = $i + 1;
			if ($next < $count && $codepoints[$next] === self::EMOJI_SELECTOR) {
				$next++;
			}
			if ($next < $count && $codepoints[$next] === self::KEYCAP) {
				return [$next - $i + 1, self::PRESENTATION_EMOJI];
			}

			// A digit is otherwise text, even with a selector after it, and is left to the font it
			// is in: nothing but a keycap makes it worth changing font for
			return null;
		}

		// Nothing else below the copyright sign is an emoji
		if ($first < 0xA9) {
			return null;
		}

		if (!self::startsElement($first)) {
			return null;
		}

		list($length, $presentation) = self::element($codepoints, $i, $count);
		$end = $i + $length;

		// A ZWJ sequence, such as 👨‍👩‍👧: each emoji joined on by U+200D makes the whole one cluster, drawn in colour
		while ($end + 1 < $count && $codepoints[$end] === self::ZWJ && self::startsElement($codepoints[$end + 1])) {
			list($joined) = self::element($codepoints, $end + 1, $count);
			$end += 1 + $joined;
			$presentation = self::PRESENTATION_EMOJI;
		}

		return [$end - $i, $presentation];
	}

	/**
	 * Whether an emoji other than a keycap or a flag can start here.
	 *
	 * Extended_Pictographic holds every emoji but the keycap bases, the regional indicators and the
	 * skin tones, so with those handled apart it stands for Emoji=Yes as well.
	 *
	 * @param int $codepoint
	 *
	 * @return bool
	 */
	private static function startsElement($codepoint)
	{
		return self::isExtendedPictographic($codepoint) || self::isModifier($codepoint);
	}

	/**
	 * Measures one emoji and anything attached to it: a presentation selector, a skin tone, or tags
	 *
	 * @param int[] $codepoints The run of text
	 * @param int   $i          The index the emoji starts at
	 * @param int   $count      The number of codepoints in the run
	 *
	 * @return array [length in codepoints, PRESENTATION_* constant]
	 */
	private static function element(array $codepoints, $i, $count)
	{
		$base = $codepoints[$i];
		$next = $i + 1;
		$presentation = self::hasEmojiPresentation($base) ? self::PRESENTATION_EMOJI : self::PRESENTATION_DEFAULT;

		// U+FE0F asks for colour and U+FE0E for text
		if ($next < $count && $codepoints[$next] === self::EMOJI_SELECTOR) {
			$presentation = self::PRESENTATION_EMOJI;
			$next++;
		} elseif ($next < $count && $codepoints[$next] === self::TEXT_SELECTOR) {
			return [$next - $i + 1, self::PRESENTATION_TEXT];
		}

		// A skin tone, where the emoji takes one
		if ($next < $count && self::isModifier($codepoints[$next]) && self::isModifierBase($base)) {
			return [$next - $i + 1, self::PRESENTATION_EMOJI];
		}

		// A tag sequence, such as the flag of England: tag characters ended by U+E007F
		$tags = $next;
		while ($tags < $count && self::isTag($codepoints[$tags]) && $codepoints[$tags] !== self::CANCEL_TAG) {
			$tags++;
		}
		if ($tags > $next && $tags < $count && $codepoints[$tags] === self::CANCEL_TAG) {
			return [$tags - $i + 1, self::PRESENTATION_EMOJI];
		}

		return [$next - $i, $presentation];
	}

	/**
	 * Whether a codepoint is in one of a property's tables, by binary search
	 *
	 * @param int[][] $ranges    [first, last] pairs in codepoint order
	 * @param int     $codepoint
	 *
	 * @return bool
	 */
	private static function inRanges(array $ranges, $codepoint)
	{
		$low = 0;
		$high = count($ranges) - 1;

		while ($low <= $high) {
			$middle = ($low + $high) >> 1;
			if ($codepoint < $ranges[$middle][0]) {
				$high = $middle - 1;
			} elseif ($codepoint > $ranges[$middle][1]) {
				$low = $middle + 1;
			} else {
				return true;
			}
		}

		return false;
	}
}
